package aprove.verification.oldframework.IntTRS.CaseAnalysis;

import java.math.*;
import java.util.*;
import java.util.Map.Entry;

import aprove.*;
import aprove.solver.Engines.*;
import aprove.solver.Engines.SMTEngine.*;
import aprove.strategies.Abortions.*;
import aprove.verification.dpframework.BasicStructures.*;
import aprove.verification.dpframework.IDPProblem.*;
import aprove.verification.oldframework.Algebra.Polynomials.*;
import aprove.verification.oldframework.BasicStructures.*;
import aprove.verification.oldframework.IntTRS.*;
import aprove.verification.oldframework.IntTRS.PoloRedPair.*;
import aprove.verification.oldframework.IntTRS.PoloRedPair.CoefficientConstraint.*;
import aprove.verification.oldframework.IntTRS.Ranking.*;
import aprove.verification.oldframework.IntTRS.RankingRedPair.*;
import aprove.verification.oldframework.LinearArithmetic.Structure.*;
import aprove.verification.oldframework.Logic.*;
import aprove.verification.oldframework.PropositionalLogic.*;
import aprove.verification.oldframework.PropositionalLogic.SMTLIB.*;
import aprove.verification.oldframework.Utility.*;
import aprove.verification.oldframework.Utility.GenericStructures.*;

/**
 * Finds a decreasing linear interpretation using an SMT-Solver. TODO: DOKU!!!
 * @author Matthias Hoelzel
 */
public class DecreasingInterpretationFinder {
    /** The input system. MIND THE GAP! */
    private final IRSwTProblem system;

    /** Some aborter - aborts and disturbs! */
    private final Abortion aborter;

    /** Some fresh name generator. */
    private final FreshNameGenerator ng;

    /** The result generated by this process. */
    private GEZeroCondition result;

    /** The input rules are translated into transition relation. */
    private LinkedList<TransitionRelation> transitionRelations;

    /** Set of occurring function symbols. */
    private LinkedHashSet<FunctionSymbol> symbols;

    /** Formula factory. Required to build formulae. */
    private final FormulaFactory<SMTLIBTheoryAtom> factory;

    /** Maps linear terms to their interpretations */
    private LinkedHashMap<FunctionSymbol, Pair<TRSFunctionApplication, VarPolynomial>> interpretationTemplate;

    /** Stores the upper bounds, if the SMT-Solver deduced some. */
    private LinkedHashMap<TransitionRelation, SimplePolynomial> upperBounds;

    /**
     * Stores the constraints ensuring the strict decrease of the
     * interpretation.
     */
    private LinkedHashMap<TransitionRelation, List<CoefficientConstraint>> strictDecreasingConstraints;

    /** Stores the constraints ensuring the weak decrease of the interpretation. */
    private LinkedHashMap<TransitionRelation, List<CoefficientConstraint>> weakDecreasingConstraints;

    /** Stores the constraints ensuring the existance of upper bounds. */
    private LinkedHashMap<TransitionRelation, List<CoefficientConstraint>> upperBoundConstraints;

    /** Stores the model generated by the SMT-Solver. In case of failure: null. */
    private Map<String, PreciseRational> model;

    /**
     * Constructor!
     * @param inputSystem the input rewrite system
     * @param formulaFactory formula factory
     * @param abortion some aborter
     * @param gen some fresh name generator
     */
    public DecreasingInterpretationFinder(
        final IRSwTProblem inputSystem,
        final FormulaFactory<SMTLIBTheoryAtom> formulaFactory,
        final Abortion abortion,
        final FreshNameGenerator gen)
    {
        this.system = inputSystem;
        this.aborter = abortion;
        this.ng = gen;
        this.factory = formulaFactory;

        assert inputSystem != null && formulaFactory != null && abortion != null && gen != null : "NULL!";
    }

    /**
     * Finds the inductive condition by constructing a decreasing interpretation, which may or may not
     * be bounded _above_ by some rules. Then the interpretation will eventually stay below the maximal upper bound.
     * @return the syntesized condition
     * @throws AbortionException can be aborted
     */
    public GEZeroCondition findInductiveCondition() throws AbortionException {
        if (this.result != null) {
            return this.result;
        }

        if (Globals.DEBUG_MATTHIAS) {
            final DebugLogger l = DebugLogger.getLogger("dif");
            l.logln("DecreasingInterpretationFinder: ");
            l.logln(this.system.toString());
            l.logln();
        }

        // 1. Translate the rules into transition relations
        this.translateRule();
        if (Globals.DEBUG_MATTHIAS) {
            final DebugLogger l = DebugLogger.getLogger("dif");
            l.logln("Translated into transition relations: ");
            for (final TransitionRelation tranRel : this.transitionRelations) {
                l.logln(tranRel);
            }
            l.logln();
        }

        // 2. Collect function symbols
        this.findFunctionSymbols();
        if (Globals.DEBUG_MATTHIAS) {
            final DebugLogger l = DebugLogger.getLogger("dif");
            l.logln("Symbols: ");
            l.logln(this.symbols);
            l.logln();
        }

        // 3. Build interpretation template
        this.buildInterpretationTemplate();
        if (Globals.DEBUG_MATTHIAS) {
            final DebugLogger l = DebugLogger.getLogger("dif");
            l.logln("Template: ");
            l.logln(this.interpretationTemplate);
            l.logln();
        }

        // 4. Try to find a decreasing interpretation
        this.findInterpretation();
        if (Globals.DEBUG_MATTHIAS) {
            final DebugLogger l = DebugLogger.getLogger("dif");

            l.logln("Model:");
            l.logln(this.model);
            l.logln();
        }

        // 5. Construct result
        this.constructResult();
        if (Globals.DEBUG_MATTHIAS) {
            final DebugLogger l = DebugLogger.getLogger("dif");
            l.logln("Result:");
            l.logln(this.result);
            DebugLogger.finishLog("dif");
        }

        return this.result;
    }

    /**
     * Translates the rule into transition relations.
     * @throws AbortionException can be aborted.
     */
    private void translateRule() throws AbortionException {
        this.transitionRelations = new LinkedList<TransitionRelation>();
        final RuleToTransitionRelation rttr = new RuleToTransitionRelation(this.ng, this.aborter);
        for (final IGeneralizedRule iRule : this.system.getRules()) {
            this.transitionRelations.add(rttr.ruleToTransitionRelation(iRule, false));
        }
    }

    /**
     * Find the defined symbols.
     */
    private void findFunctionSymbols() {
        this.symbols = new LinkedHashSet<>();
        for (final TransitionRelation tranRel : this.transitionRelations) {
            this.symbols.add(tranRel.getStartSymbol());
            this.symbols.add(tranRel.getEndSymbol());
        }
    }

    /**
     * Uses the defined symbol to construct an abstract interpretations template.
     * Here abtract means that there are some unknown coefficients to be instantiated by
     * concrete values.
     */
    private void buildInterpretationTemplate() {
        this.interpretationTemplate = new LinkedHashMap<>();
        for (final FunctionSymbol sym : this.symbols) {
            final ArrayList<TRSVariable> args = new ArrayList<>(sym.getArity());
            VarPolynomial template = VarPolynomial.ZERO;
            for (int i = 0; i < sym.getArity(); i++) {
                final String varName = this.ng.getFreshName("x", false);
                args.add(TRSTerm.createVariable(varName));
                final String coeffName = this.ng.getFreshName("m", false);
                template =
                    template.plus(VarPolynomial.createCoefficient(coeffName).times(
                        VarPolynomial.createVariable(varName)));
            }

            this.interpretationTemplate.put(
                sym,
                new Pair<TRSFunctionApplication, VarPolynomial>(
                    TRSTerm.createFunctionApplication(sym, args),
                    template));
        }
    }

    /**
     * Constructs a big SMT-formula to find a decreasing interpretation and some
     * upper bounds.
     * @throws AbortionException can be aborted
     */
    private void findInterpretation() throws AbortionException {
        // 1. Construction of the SMT-formula:
        final Formula<SMTLIBTheoryAtom> toSolve = this.generateSMTFormulae();
        if (Globals.DEBUG_MATTHIAS) {
            final DebugLogger l = DebugLogger.getLogger("dif");
            l.logln("Formula: " + toSolve);
        }

        // 2. Invoke SMT-Solver to find a solution:
        final SMTEngine smtEngine = new YicesEngine();
        Pair<YNM, Map<String, String>> smtSolverResult;
        try {
            smtSolverResult = smtEngine.solve(Collections.singletonList(toSolve), SMTLogic.QF_LRA, this.aborter);
        } catch (final WrongLogicException wle) {
            System.err.println("Solver exception: " + wle);
            smtSolverResult = new Pair<YNM, Map<String, String>>(YNM.MAYBE, null);
        }

        if (smtSolverResult.x == YNM.YES) {
            this.model = ToolBox.parseRationalInterpretation(smtSolverResult.y);
        } else {
            this.model = null;
        }
    }

    /**
     * Generates the SMT-formulae that expresses properties that our interpretation
     * should have. These properties (decreasing, upper bounds) are found in form of
     * non-negative linear combinations of the given conditions.
     * @return an SMT-formula.
     * @throws AbortionException can be aborted
     */
    private Formula<SMTLIBTheoryAtom> generateSMTFormulae() throws AbortionException {
        this.upperBounds = new LinkedHashMap<>();
        this.strictDecreasingConstraints = new LinkedHashMap<>();
        this.weakDecreasingConstraints = new LinkedHashMap<>();
        this.upperBoundConstraints = new LinkedHashMap<>();

        final LinkedList<Formula<SMTLIBTheoryAtom>> strictDecreaseFormulae = new LinkedList<>();
        final LinkedList<Formula<SMTLIBTheoryAtom>> decreaseOrBoundedFormulae = new LinkedList<>();

        for (final TransitionRelation tranRel : this.transitionRelations) {
            this.generateFormulaeForRelation(strictDecreaseFormulae, decreaseOrBoundedFormulae, tranRel);
        }

        final Formula<SMTLIBTheoryAtom> toSolve =
            this.factory.buildAnd(
                this.factory.buildOr(strictDecreaseFormulae),
                this.factory.buildAnd(decreaseOrBoundedFormulae));
        return toSolve;
    }

    /**
     * Is called by generateSMTFormulae() for each transition relation tranRel
     * @param strictDecreaseFormulae list to fill in formulae for the strict decrease
     * @param decreaseOrBoundedFormulae list to fill in formulae for the weak decrease
     * @param tranRel the currently considered transition relation
     * @throws AbortionException can be aborted
     */
    private void generateFormulaeForRelation(
        final LinkedList<Formula<SMTLIBTheoryAtom>> strictDecreaseFormulae,
        final LinkedList<Formula<SMTLIBTheoryAtom>> decreaseOrBoundedFormulae,
        final TransitionRelation tranRel) throws AbortionException
    {
        if (Globals.DEBUG_MATTHIAS) {
            final DebugLogger l = DebugLogger.getLogger("dif");
            l.logln("Generating formulae for relation:");
            l.logln(tranRel);
            l.logln();
        }

        final List<TRSVariable> startVariables = tranRel.getStartVariables();
        final List<TRSVariable> endVariables = tranRel.getEndVariables();

        // Get templates:
        final Pair<TRSFunctionApplication, VarPolynomial> startTemplate =
            this.interpretationTemplate.get(tranRel.getStartSymbol());
        final Pair<TRSFunctionApplication, VarPolynomial> endTemplate =
            this.interpretationTemplate.get(tranRel.getEndSymbol());
        if (Globals.DEBUG_MATTHIAS) {
            final DebugLogger l = DebugLogger.getLogger("dif");
            l.logln("startTemplate = " + startTemplate);
            l.logln("endTemplate = " + endTemplate);
            l.logln();
        }

        // Substitute the correct variables:
        final Map<String, VarPolynomial> leftSubstitution =
            DecreasingInterpretationFinder.calculateNameSubstitution(startVariables, startTemplate.getKey());
        final Map<String, VarPolynomial> rightSubstitution =
            DecreasingInterpretationFinder.calculateNameSubstitution(endVariables, endTemplate.getKey());
        if (Globals.DEBUG_MATTHIAS) {
            final DebugLogger l = DebugLogger.getLogger("dif");
            l.logln("leftSubstitution = " + leftSubstitution);
            l.logln("rightSubstitution = " + rightSubstitution);
            l.logln();
        }

        // Substituted interpretation template:
        final VarPolynomial leftInterpretation = startTemplate.getValue().substituteVariables(leftSubstitution);
        final VarPolynomial rightInterpretation = endTemplate.getValue().substituteVariables(rightSubstitution);

        final VarPolynomial leftMinusRight = leftInterpretation.minus(rightInterpretation);

        if (Globals.DEBUG_MATTHIAS) {
            final DebugLogger l = DebugLogger.getLogger("dif");
            l.logln("leftInterpretation = " + leftInterpretation);
            l.logln("rightInterpretation = " + rightInterpretation);
            l.logln("leftMinusRight = " + leftMinusRight);
            l.logln();
        }

        // Build linear combinations:
        final LinearCombination lcDecrease = tranRel.getPCS().toLinearCombination(this.ng);
        final LinearCombination lcUpperBound = tranRel.getPCS().toLinearCombination(this.ng);

        if (Globals.DEBUG_MATTHIAS) {
            final DebugLogger l = DebugLogger.getLogger("dif");
            l.logln("lcDecrease = " + lcDecrease);
            l.logln("lcUpperBound = " + lcUpperBound);
            l.logln();
        }

        // Combine linear combinations with interpretation templates:
        final VarPolynomial decreaseToBeZero = lcDecrease.getLeftSide().minus(leftMinusRight);
        final VarPolynomial upperBoundToBeZero = lcUpperBound.getLeftSide().plus(rightInterpretation);

        if (Globals.DEBUG_MATTHIAS) {
            final DebugLogger l = DebugLogger.getLogger("dif");
            l.logln("decreaseToBeZero = " + decreaseToBeZero);
            l.logln("upperBoundToBeZero = " + upperBoundToBeZero);
            l.logln();
        }

        // Build SMT-formulae:
        final Formula<SMTLIBTheoryAtom> strictDecreaseFormula =
            this.buildStrictDecreaseFormula(tranRel, decreaseToBeZero, lcDecrease);
        final Formula<SMTLIBTheoryAtom> weakDecreaseFormula =
            this.buildWeakDecreaseFormula(tranRel, decreaseToBeZero, lcDecrease);
        final Formula<SMTLIBTheoryAtom> upperBoundFormula =
            this.buildUpperBoundFormula(tranRel, upperBoundToBeZero, lcUpperBound);

        decreaseOrBoundedFormulae.add(this.factory.buildOr(weakDecreaseFormula, upperBoundFormula));
        strictDecreaseFormulae.add(strictDecreaseFormula);
    }

    /**
     * Builds an SMT-formula that expresses an upper bound for our interpretation.
     * @param tranRel currently considered transition relation
     * @param upperBoundToBeZero some polynomial
     * @param lcUpperBound linear combination of the given transition relation
     * @return some SMT-formula
     */
    private Formula<SMTLIBTheoryAtom> buildUpperBoundFormula(
        final TransitionRelation tranRel,
        final VarPolynomial upperBoundToBeZero,
        final LinearCombination lcUpperBound)
    {
        final LinkedList<CoefficientConstraint> ccList = new LinkedList<>();

        this.forceCoefficientsToBeZero(ccList, upperBoundToBeZero);
        this.buildCorrectLinearCombination(ccList, lcUpperBound);

        this.upperBoundConstraints.put(tranRel, ccList);
        this.upperBounds.put(tranRel, lcUpperBound.getRightSide().negate());

        if (Globals.DEBUG_MATTHIAS) {
            final DebugLogger l = DebugLogger.getLogger("dif");
            l.logln("Upper bound formulae:");
            l.logln(ccList);
            l.logln();
        }

        return this.convertCCListToSMTFormula(ccList);
    }

    /**
     * Builds an SMT-formula that expresses an weak decrease for our interpretation.
     * @param tranRel some transition relation
     * @param decreaseToBeZero some polynomial
     * @param lcDecrease currently used linear combination
     * @return some SMT-formula
     */
    private Formula<SMTLIBTheoryAtom> buildWeakDecreaseFormula(
        final TransitionRelation tranRel,
        final VarPolynomial decreaseToBeZero,
        final LinearCombination lcDecrease)
    {
        final LinkedList<CoefficientConstraint> ccList = new LinkedList<>();

        this.forceCoefficientsToBeZero(ccList, decreaseToBeZero);
        ccList.add(new CoefficientConstraint(lcDecrease.getRightSide(), CoefficientConstraintType.GE_ZERO));
        this.buildCorrectLinearCombination(ccList, lcDecrease);

        this.weakDecreasingConstraints.put(tranRel, ccList);

        if (Globals.DEBUG_MATTHIAS) {
            final DebugLogger l = DebugLogger.getLogger("dif");
            l.logln("Weak decreasing formulae:");
            l.logln(ccList);
            l.logln();
        }

        return this.convertCCListToSMTFormula(ccList);
    }

    /**
     * Builds an SMT-formula that expresses an strict decrease for our interpretation.
     * @param tranRel some transition relation
     * @param decreaseToBeZero some polynomial
     * @param lcDecrease currently used linear combination
     * @return some SMT-formula
     */
    private Formula<SMTLIBTheoryAtom> buildStrictDecreaseFormula(
        final TransitionRelation tranRel,
        final VarPolynomial decreaseToBeZero,
        final LinearCombination lcDecrease)
    {
        final LinkedList<CoefficientConstraint> ccList = new LinkedList<>();

        this.forceCoefficientsToBeZero(ccList, decreaseToBeZero);
        this.buildCorrectLinearCombination(ccList, lcDecrease);
        ccList.add(new CoefficientConstraint(lcDecrease.getRightSide(), CoefficientConstraintType.GT_ZERO));

        this.strictDecreasingConstraints.put(tranRel, ccList);

        if (Globals.DEBUG_MATTHIAS) {
            final DebugLogger l = DebugLogger.getLogger("dif");
            l.logln("Strict decreasing formulae:");
            l.logln(ccList);
            l.logln();
        }

        return this.convertCCListToSMTFormula(ccList);
    }

    /**
     * A linear combination is only useful for our purposes if its coefficients are non-negative.
     * @param ccList list of constraints to be completed.
     * @param lc a linear combination.
     */
    private void buildCorrectLinearCombination(
        final LinkedList<CoefficientConstraint> ccList,
        final LinearCombination lc)
    {
        for (final String coeff : lc.getCoefficients()) {
            ccList.add(new CoefficientConstraint(SimplePolynomial.create(coeff), CoefficientConstraintType.GE_ZERO));
        }
    }

    /**
     * Function that generates constraint that enforce that a given polynomial is identically zero.
     * @param ccList list of constraints to be completed
     * @param toBeZero polynomial to be identically zero, i.e. every coefficient is zero.
     */
    private
        void
        forceCoefficientsToBeZero(final LinkedList<CoefficientConstraint> ccList, final VarPolynomial toBeZero)
    {
        for (final SimplePolynomial coeff : toBeZero.getVarMonomials().values()) {
            ccList.add(new CoefficientConstraint(coeff, CoefficientConstraintType.EQ_ZERO));
        }
    }

    /**
     * Convert the constraints into an SMT-formula.
     * @param ccList list of input constraints
     * @return an SMT-formula
     */
    private Formula<SMTLIBTheoryAtom> convertCCListToSMTFormula(final LinkedList<CoefficientConstraint> ccList) {
        final LinkedList<Formula<SMTLIBTheoryAtom>> converted = new LinkedList<>();
        for (final CoefficientConstraint cc : ccList) {
            converted.add(this.factory.buildTheoryAtom(cc.toSMTLIBRatTheoryAtom()));
        }
        return this.factory.buildAnd(converted);
    }

    /**
     * Replaces the given variable by the variable which occur in a function application.
     * @param variables list of variables
     * @param funcy a function application
     * @return maps the variables (in of string) to the arguments (in form of polynomials)
     */
    private static Map<String, VarPolynomial> calculateNameSubstitution(
        final List<TRSVariable> variables,
        final TRSFunctionApplication funcy
    ) {
        final List<TRSTerm> args = funcy.getArguments();
        final Iterator<TRSVariable> varIter = variables.iterator();
        final Iterator<TRSTerm> argIter = args.iterator();
        assert variables.size() == funcy.getRootSymbol().getArity() : "Invalid arities!";
        final LinkedHashMap<String, VarPolynomial> result = new LinkedHashMap<>();
        while (varIter.hasNext() && argIter.hasNext()) {
            final TRSVariable nextVar = varIter.next();
            final TRSTerm nextArg = argIter.next();
            assert nextArg.isVariable() : "Invalid template!";
            result.put(((TRSVariable) nextArg).getName(), VarPolynomial.createVariable(nextVar.getName()));
        }
        return result;
    }

    /**
     * If SMT-Solver found a model, then we have our interpretation and thus we obtain
     * the inductive condition.
     */
    private void constructResult() {
        if (this.model == null) {
            // No model -> can't do anything!
            return;
        }
        // Calculate a integer model:
        // To do obtain such a thing, calculate the lcm of the denominators:
        final Set<BigInteger> denominators = new LinkedHashSet<>();
        for (final PreciseRational x : this.model.values()) {
            denominators.add(x.getDenominator());
        }
        final BigInteger lcm = DecreasingInterpretationFinder.getLCM(denominators);
        // Multiplying preserves the inequalities:
        final LinkedHashMap<String, BigInteger> integerModel = new LinkedHashMap<>();
        for (final Entry<String, PreciseRational> e : this.model.entrySet()) {
            final PreciseRational rp = e.getValue().multiply(new PreciseRational(lcm));
            assert rp.getDenominator().equals(BigInteger.ONE);
            integerModel.put(e.getKey(), rp.getNumerator());
        }
        // Which relations are bounded?
        final LinkedHashSet<BigInteger> bounds = new LinkedHashSet<>();
        for (final TransitionRelation tranRel : this.transitionRelations) {
            if (this.isSatisfied(this.upperBoundConstraints.get(tranRel))) {
                bounds.add(this.upperBounds.get(tranRel).interpret(integerModel, BigInteger.ZERO));
            }
        }
        if (Globals.DEBUG_MATTHIAS) {
            final DebugLogger l = DebugLogger.getLogger("dif");
            l.logln("Got the following bounds: " + bounds);
        }
        if (bounds.isEmpty()) {
            bounds.add(BigInteger.valueOf(-1));
            if (Globals.DEBUG_MATTHIAS) {
                final DebugLogger l = DebugLogger.getLogger("dif");
                l.logln("Empty -> Adding (-1).");
            }
        }
        final BigInteger maxBound = ToolBox.max(bounds);
        // Build the concrete interpretation:
        final LinkedHashMap<FunctionSymbol, Pair<TRSFunctionApplication, VarPolynomial>> terms = new LinkedHashMap<>();
        final VarPolynomial maxBoundPoly = VarPolynomial.create(maxBound);
        for (
            final Entry<FunctionSymbol, Pair<TRSFunctionApplication, VarPolynomial>> e :
                this.interpretationTemplate.entrySet()
        ) {
            final Pair<TRSFunctionApplication, VarPolynomial> p = e.getValue();
            final VarPolynomial interpretedPoly = maxBoundPoly.minus(p.getValue().specialize(integerModel));
            assert interpretedPoly.isConcrete() : "Interpretation did not interpret every variable!";
            terms.put(e.getKey(), new Pair<TRSFunctionApplication, VarPolynomial>(p.getKey(), interpretedPoly));
        }
        this.result = new GEZeroCondition(terms);
    }

    /**
     * Checks whether or not the given model (computed by an SMT-Solver!) satisfies
     * some constraints.
     * @param ccList list of some constraints
     * @return true or false
     */
    private boolean isSatisfied(final List<CoefficientConstraint> ccList) {
        for (final CoefficientConstraint cc : ccList) {
            if (!cc.isSatisfiedByRationalAssignment(this.model)) {
                return false;
            }
        }
        return true;
    }

    /**
     * Computes the least common multiple of some integers.
     * @param numbers some integers (BigIntegers)
     * @return the lcm of numbers
     */
    private static BigInteger getLCM(final Set<BigInteger> numbers) {
        BigInteger result = BigInteger.ONE;
        for (final BigInteger x : numbers) {
            result = x.multiply(result).divide(result.gcd(x));
        }
        return result;
    }
}
