package aprove.verification.oldframework.PropositionalLogic.SATCheckers;

import java.io.*;
import java.util.*;
import java.util.logging.*;

import org.sat4j.core.*;
import org.sat4j.specs.*;

import aprove.*;
import aprove.strategies.Abortions.*;
import aprove.verification.oldframework.PropositionalLogic.*;
import aprove.verification.oldframework.PropositionalLogic.Formulae.*;
import aprove.verification.oldframework.PropositionalLogic.TheoryPropositions.*;

public class MiniSATFileChecker extends AbstractSATChecker {

    public class MSFCExecException extends Exception {

        // generated by Eclipse to avoid warning
        private static final long serialVersionUID = 5576969544963604633L;

        public MSFCExecException(final Throwable cause) {
            super(cause);
        }
    }

    private final String COMMAND;

    private final boolean tseitin;
    private final boolean newDimacsGen;

    private final boolean xorClauses; // use special XOR solving?

    protected Set<Formula<None>> assumps = new LinkedHashSet<Formula<None>>();
    protected boolean hasAssumps = false;

    /**
     * @param version - the version of MiniSAT (for non-integral version
     *   numbers like 2.2, write e.g. 22)
     * @param simp - use preprocessor to simplify clauses before SAT solving?
     * @param assumps - use assumptions? (if you don't know what that is,
     *  false is a good value here)
     * @param tseitin - use Tseitin's transformation (instead of the external
     *  tool BC2SAT) to convert the propositional formula to a CNF -- here
     *  true is a good idea
     * @param xorClauses - experimental feature to support dedicated
     *  xorClauses (non-standard), setting to false is a very good idea
     *  if you are not actively working on this
     * @param xorLight - determines the level of xor-based calculations
     *  for solving with the xorClauses feature (don't care otherwise)
     * @param xorAssert - when using xorClauses, use a solver version with
     *  assertions enabled? (don't care otherwise)
     * @param newDimacsGen - use AProVE's own Tseitin implementation instead
     *  of the one in SAT4J? Here false is a good idea since AProVE's
     *  implementation is slightly slower than SAT4J's, possibly because
     *  of the overhead of the visitor pattern used here
     * @param prefetchHeader - use header prefetching?
     *  (ignored if version != 2). Not much testing done here,
     *  so in doubt set to false.
     * @param prefetchLists - use watch lists prefetching?
     *  (ignored if version != 2). Not much testing done here,
     *  so in doubt set to false.
     */
    public MiniSATFileChecker(
        final int version,
        final boolean simp,
        final boolean assumps,
        final boolean tseitin,
        final boolean xorClauses,
        final boolean xorLight,
        final boolean xorAssert,
        final boolean newDimacsGen,
        final boolean prefetchHeader,
        final boolean prefetchLists)
    {
        // TODO maybe use wrapper class for all those flags,
        // e.g., MiniSATConfigInfo; essentially this could be an
        // Immutable version of MINISATEngine.Arguments

        String command;
        if (xorClauses) {
            final StringBuilder cmd = new StringBuilder("xor-");
            cmd.append(xorLight ? "light-" : "full-");
            cmd.append(xorAssert ? "assert" : "release");
            command = cmd.toString();
            // XOR MiniSAT executable names may change in the future
        } else if (version < 2) {
            command = "minisat1";
        } else if (version == 22) {
            command = simp ? "minisat22simp" : "minisat22core";
        } else if (assumps) {
            command = "minisat2assumps";
            this.hasAssumps = true;
        } else if (prefetchHeader || prefetchLists) {
            final StringBuilder cmd = new StringBuilder(32);
            cmd.append("minisat2");
            cmd.append(simp ? "simpP" : "coreP");
            if (!prefetchHeader) {
                cmd.append("lists");
            } else if (!prefetchLists) {
                cmd.append("header");
            } else {
                cmd.append("both");
            }
            command = cmd.toString();
        } else if (simp) {
            command = "minisat2simp";
        } else {
            command = "minisat2core";
        }
        if (MiniSATExtStartedFileChecker.found(command)) {
            this.COMMAND = command;
        } else if (MiniSATExtStartedFileChecker.found("minisat")) {
            // fallback (for GUI users?)
            this.COMMAND = "minisat";
        } else {
            System.err.println("Please install minisat2.");
            this.COMMAND = null;
        }

        this.tseitin = tseitin;
        this.newDimacsGen = newDimacsGen;
        this.xorClauses = xorClauses;
    }

    @Override
    public void setAssumps(final Set<Formula<None>> assumps) {
        this.assumps = assumps;
    }

    @Override
    public int[] solve(final Formula<None> formula, final Abortion aborter) throws AbortionException, SolverException {
        String dimacsOrIscas;
        if (!this.newDimacsGen) {
            if (this.tseitin) {
                dimacsOrIscas = FormulaToDimacsConverter.convert(formula, this.xorClauses, aborter);
                if (AbstractSATChecker.log.isLoggable(Level.FINEST)) {
                    AbstractSATChecker.log.log(Level.FINE, "CNF length in characters: {0}\n", dimacsOrIscas.length());
                    final int nlPos = dimacsOrIscas.indexOf("\n");
                    AbstractSATChecker.log.fine("First line of "
                        + (this.xorClauses ? "XOR" : "")
                        + "DIMACS problem (# vars, # clauses):\n"
                        + dimacsOrIscas.substring(0, nlPos + 1));
                }
            } else {
                dimacsOrIscas = FormulaToDimacsConverter.convertToIscas(formula, aborter);
                if (AbstractSATChecker.log.isLoggable(Level.FINEST)) {
                    AbstractSATChecker.log.log(Level.FINE, "ISCAS length in characters: {0}\n", dimacsOrIscas.length());
                }
            }
            aborter.checkAbortion();
            return this.solve(dimacsOrIscas, aborter);
        } else {
            File input = null;
            File output = null;
            try {
                // New handling
                aborter.checkAbortion();
                input = File.createTempFile("aproveMiniSAT", ".dimacs");
                input.deleteOnExit();
                output = File.createTempFile("aproveMiniSAT", ".output");
                output.deleteOnExit();
                FormulaToDimacsConverter.convertAndWrite(input, formula);
                aborter.checkAbortion();
                return this.solve(input, output, aborter);
            } catch (final IOException e) {
                e.printStackTrace();
            } finally {
                if (input != null) {
                    input.delete();
                }
                if (output != null) {
                    output.delete();
                }
            }
            throw new SolverException();

        }
    }

    @Override
    public int[] solve(String dimacs, final Abortion aborter) throws AbortionException, SolverException {
        File input = null;
        File output = null;

        try {
            aborter.checkAbortion();
            //    input = File.createTempFile("aproveMiniSAT",".dimacs", curDir);
            input =
                File.createTempFile("aproveMiniSAT", this.xorClauses ? ".xordimacs" : (this.tseitin
                    ? ".dimacs"
                        : ".iscas"));
            input.deleteOnExit();
            final Writer inputWriter = new OutputStreamWriter(new FileOutputStream(input));
            //            long time = System.nanoTime();
            inputWriter.write(dimacs);
            //            long diff = System.nanoTime()-time;
            //            System.err.println("Writing MINISAT file ("+(dimacsOrIscas.length()/1024)+"kb) need " + diff + " ns");
            dimacs = null;
            inputWriter.close();
            aborter.checkAbortion();
            //output = File.createTempFile("aproveMiniSAT",".output", curDir);
            output = File.createTempFile("aproveMiniSAT", ".output");
            output.deleteOnExit();
            return this.solve(input, output, aborter);
        } catch (final NoSuchElementException e) {
            // just return null
        } catch (final IOException e) {
            e.printStackTrace();
        } finally {
            if (input != null) {
                input.delete();
            }
            if (output != null) {
                output.delete();
            }
        }
        throw new SolverException();

    }

    public int[] solve(final File input, final File output, final Abortion aborter)
        throws AbortionException,
            SolverException
    {
        final Process process;
        File dimacsFromBC2SAT = null;
        try {
            aborter.checkAbortion();
            String args = "";
            if (this.hasAssumps == true) {
                args = "-assumptions ";

                for (final Formula<None> f : this.assumps) {
                    if (f instanceof Variable) {
                        args = args + Integer.toString(f.getId()) + " ";
                    } else if (f instanceof NotFormula) {
                        if (((NotFormula<None>) f).isLiteral()) {
                            args = args + Integer.toString(((NotFormula<None>) f).getLiteralId()) + " ";
                        }
                    }
                }
                args = args + "0 ";
            }

            AbstractSATChecker.log.log(Level.FINER, this.tseitin ? "DIMACS to {0}\n" : "ISCAS to {0}\n", input.getCanonicalPath());
            AbstractSATChecker.log.log(Level.FINER, "OUTPUT to {0}\n", output.getCanonicalPath());

            //ProcessBuilder pb = new ProcessBuilder(COMMAND, input.getCanonicalPath(), output.getCanonicalPath());
            //pb.redirectErrorStream(true);
            //process = pb.start();
            //process = Runtime.getRuntime().exec(COMMAND + " "+input.getCanonicalPath()+" "+output.getCanonicalPath());
            if (this.tseitin) {
                AbstractSATChecker.log.log(Level.FINER, "Invoking {0}\n", this.COMMAND + args);
                AbstractSATChecker.log.log(
                    Level.FINE,
                    this.COMMAND + args + " " + input.getCanonicalPath() + " " + output.getCanonicalPath());
                String[] runMe;
                // beware of putting the empty String in there
                if (args.length() > 0) {
                    runMe = new String[] {this.COMMAND, args, input.getCanonicalPath(), output.getCanonicalPath() };
                } else {
                    runMe = new String[] {this.COMMAND, input.getCanonicalPath(), output.getCanonicalPath() };
                }
                aborter.checkAbortion();
                try {
                    process = Runtime.getRuntime().exec(runMe);
                } catch (final IOException e) {
                    throw new MSFCExecException(e);
                }
            } else {
                aborter.checkAbortion();
                dimacsFromBC2SAT = File.createTempFile("aproveMiniSAT", ".dimacs");
                dimacsFromBC2SAT.deleteOnExit();
                final String dimacsPath = dimacsFromBC2SAT.getCanonicalPath();
                final String cmdLine =
                    "bc2sat "
                        + input.getCanonicalPath()
                        + " > "
                        + dimacsPath
                        + " ; "
                        + this.COMMAND
                        + args
                        + " "
                        + dimacsPath
                        + " "
                        + output.getCanonicalPath();
                AbstractSATChecker.log.log(Level.FINER, "DIMACS to {0}\n", dimacsPath);
                AbstractSATChecker.log.log(Level.FINER, "Invoking bc2sat and {0}\n", this.COMMAND + args);
                final ProcessBuilder pb = new ProcessBuilder("bash", "-c", cmdLine);
                try {
                    process = pb.start();
                } catch (final IOException e) {
                    throw new MSFCExecException(e);
                }

            }
            TrackerFactory.process(aborter, process);
            aborter.checkAbortion();
            try (final BufferedReader stdOut = new BufferedReader(new InputStreamReader(process.getInputStream()))) {
                while (true) {
                    String line = null;
                    line = stdOut.readLine();
                    if (line == null) {
                        break;
                    }
                    if (AbstractSATChecker.log.isLoggable(Level.FINEST)) {
                        AbstractSATChecker.log.log(Level.FINEST, "{0}\n", line);
                    }
                }
            } catch (final IOException e) {
                // do nothing. MiniSAT might just be killed because of
                // some strategy reason.
            }
            aborter.checkAbortion();
            try (BufferedReader fileReader = new BufferedReader(new FileReader(output))) {
                final String result = fileReader.readLine();
                if (result == null) {
                    AbstractSATChecker.log.log(Level.FINE, "MiniSAT did not return a result!\n");
                    return null; // No result here!= MINISAT must have been killed (or some error occured)
                }
                if (!result.equals("SAT")) {
                    if (result.equals("UNSAT")) {
                        return null;
                    }
                    assert false;
                }
                aborter.checkAbortion();
                AbstractSATChecker.log.log(Level.FINE, "MiniSAT says: {0}\n", result);
                final IVecInt resVecInt = new VecInt();
                boolean endOfFile = false;
                while (!endOfFile) {
                    final String line = fileReader.readLine();
                    if (line == null || line.length() == 0) {
                        break;
                    }
                    final String[] numStrings = line.split(" ");
                    final int nums = numStrings.length;
                    for (int i = 0; i < nums; i++) {
                        if (numStrings[i].equals("0")) {
                            endOfFile = true;
                            break;
                        }
                        resVecInt.push(Integer.parseInt(numStrings[i]));
                    }
                }
                aborter.checkAbortion();
                if (this.tseitin) {
                    final int[] res = new int[resVecInt.size()];

                    // System.arraycopy() should be faster than n calls to get()
                    resVecInt.copyTo(res);
                    aborter.checkAbortion();
                    return res;
                } else { // bc2sat assigns new ids, but we need the model for the old ones
                         //  => build map which stores relation
                    final Map<Integer, Integer> newToOld = new HashMap<Integer, Integer>();
                    try (
                        final BufferedReader dimacsCommentReader = new BufferedReader(new FileReader(dimacsFromBC2SAT))) {
                        String line = dimacsCommentReader.readLine();
                        while (line != null && line.startsWith("c")) {
                            if (!line.startsWith("c ***")) { // no meta-comments, please
                                final StringTokenizer st = new StringTokenizer(line);
                                if (Globals.useAssertions) {
                                    assert st.countTokens() == 4;
                                }
                                st.nextToken(); // skip "c"
                                final String newIdString = st.nextToken();
                                st.nextToken(); // skip "="
                                final String iscasGateName = st.nextToken();
                                final char firstChar = iscasGateName.charAt(0);
                                if (firstChar == FormulaToDimacsConverter.iscasGatePrefix) {
                                    // the string to follow firstChar is the old id
                                    final String oldIdString = iscasGateName.substring(1);
                                    final int oldId = Integer.parseInt(oldIdString);
                                    final int newId = Integer.parseInt(newIdString);
                                    newToOld.put(newId, oldId);
                                } else {
                                    if (Globals.useAssertions) {
                                        assert firstChar == FormulaToDimacsConverter.addIscasGatePrefix;
                                    }
                                }
                            }
                            line = dimacsCommentReader.readLine();
                        }
                    }

                    final List<Integer> resListWithOldVars = new ArrayList<Integer>(newToOld.size());
                    final int size = resVecInt.size();
                    for (int i = 0; i < size; i++) {
                        final int resultForNewId = resVecInt.get(i);
                        final Integer oldId = newToOld.get(Math.abs(resultForNewId));
                        if (oldId != null) {
                            // convert result for new vars to result for old vars
                            final Integer resultForOldId = resultForNewId > 0 ? oldId : -oldId;
                            resListWithOldVars.add(resultForOldId);
                        }
                    }
                    final int[] res = new int[resListWithOldVars.size()];
                    for (int i = 0; i < res.length; i++) {
                        res[i] = resListWithOldVars.get(i);
                    }
                    aborter.checkAbortion();
                    return res;
                }
            }
        } catch (final NoSuchElementException e) {
            // just return null
        } catch (final MSFCExecException e) {
            AbstractSATChecker.log.log(Level.WARNING, "Error executing MiniSAT solver: " + e);
        } catch (final IOException e) {
            AbstractSATChecker.log.log(Level.CONFIG, "Error executing MiniSAT solver", e);
        } finally {

            if (dimacsFromBC2SAT != null) {
                dimacsFromBC2SAT.delete();
            }

        }
        return null;
    }

    @Override
    public int[] solveCNF(final Formula<None> formula, final Abortion aborter) {
        // TODO Auto-generated method stub
        return null;
    }

}
