package aprove.verification.oldframework.PropositionalLogic.SATCheckers;

/**
 * This exception is thrown by a SAT checker
 * if its external solver does not return a model
 * or fails in any other way.
 *
 * @author Andreas Kelle-Emden
 */
public class SolverException extends Exception {

    /**
     * Generated by Eclipse
     */
    private static final long serialVersionUID = -514904135459529969L;

    public SolverException() {
        super();
    }

    public SolverException(String message) {
        super(message);
    }

    public SolverException(Throwable cause) {
        super(cause);
    }
}
