FOLDER="example_problems"
SUBDIR="PTRS_Standard"
CATEGORY="PTRS_Standard"
TIMEOUT="10"
IMAGE="aprove_solver:java25"
OUTDIR="example_results/PTRS_Standard"
APROVE_JAR="../dist/lib/aprove.jar"
# APROVE_JAR="./Jars/all.jar"
EXTENSION="ari"
