FOLDER="example_problems"
SUBDIR="TRS_Outermost"
CATEGORY="TRS_Outermost"
TIMEOUT="10"
IMAGE="aprove_solver:java25"
OUTDIR="example_results/TRS_Outermost"
APROVE_JAR="../dist/lib/aprove.jar"
# APROVE_JAR="./Jars/all.jar"
EXTENSION="ari"
