package aprove.verification.oldframework.Unification.Utility;

import java.util.*;

import aprove.verification.oldframework.Algebra.Terms.*;
import aprove.verification.oldframework.Syntax.*;
import aprove.verification.oldframework.Utility.*;

/** Substitution of constants with terms.
 *
 * @author Stephan Falke
 * @version $Id$
 */

public class VarAbstraction {

    private  Map map;
    private  Map invMap;

    // ------------------- constructors

    private VarAbstraction() {
    this.map = new LinkedHashMap();
    this.invMap = new LinkedHashMap();
    }

    /** Aliens of s are replaced by fresh variables that are generated by fvg.
     */
    public static VarAbstraction create(ACTerm s, FreshVarGenerator fvg) {
    VarAbstraction res = new VarAbstraction();

    Sort sort = s.getSort();

    Iterator i = s.getAliens().iterator();
    while(i.hasNext()) {
        AlgebraVariable x = fvg.getFreshVariable("x", sort, false);
        res.put((ACTerm)i.next(), x);
    }

    return res;
    }

    /** Extends this VarAbstraction with the remaining aliens of s.
     */
    public void extend(ACTerm s, FreshVarGenerator fvg) {
    Sort sort = s.getSort();
    Set<ACTerm> dom = this.getDomain();

    Iterator i = s.getAliens().iterator();
    while(i.hasNext()) {
        ACTerm si = (ACTerm)i.next();
        if(!dom.contains(si)) {
            AlgebraVariable x = fvg.getFreshVariable("x", sort, false);
            this.put(si, x);
        }
    }
    }

    // ---------------- accessor methods

    /** Returns the variable the given term is mapped to by this substitution.
     * @param s  term whose mapping should be returned
     * @return Term that constant maps to
     */
    public AlgebraVariable get(ACTerm s) {
    return (AlgebraVariable)this.map.get(s);
    }

    public ACTerm invGet(AlgebraVariable x) {
    return (ACTerm)this.invMap.get(x);
    }

    /** Adds a new abstraction.
     */
    public void put(ACTerm s, AlgebraVariable x) {
    this.map.put(s, x);
    this.invMap.put(x, s);
    }

    //------------- miscellaneous methods

    /** Conversion to a string representation.
     */
    @Override
    public String toString() {
    StringBuffer temp = new StringBuffer("[");
    for (Iterator i=this.map.keySet().iterator(); i.hasNext();) {
        ACTerm t = (ACTerm)i.next();
        temp.append(t.toString() + "/" + this.map.get(t).toString());
        if (i.hasNext()) {
        temp.append(", ");
        }
    }
    temp.append("]");
    return temp.toString();
    }

    @Override
    final public boolean equals(Object o) {
    VarAbstraction s = (VarAbstraction)o;
    return this.map.equals(s.map);
    }

    @Override
    final public int hashCode() {
    return this.map.hashCode();
    }

    public Set<ACTerm> getDomain() {
    return new LinkedHashSet<ACTerm>(this.map.keySet());
    }

    public Set<AlgebraVariable> getRange() {
    return new LinkedHashSet<AlgebraVariable>(this.invMap.keySet());
    }

}
