/**
 *
 * @author noschinski
 * @version $Id$
 */

package aprove.verification.dpframework.IDPProblem.PfManager;

import java.math.*;
import java.util.*;

import aprove.verification.dpframework.BasicStructures.*;
import aprove.verification.dpframework.CLSProblem.Utility.*;
import aprove.verification.dpframework.IDPProblem.*;
import aprove.verification.dpframework.IDPProblem.PfFunctions.*;
import aprove.verification.dpframework.IDPProblem.PfFunctions.PredefinedFunction.*;
import aprove.verification.dpframework.IDPProblem.PfFunctions.domains.*;
import aprove.verification.dpframework.IDPProblem.utility.*;
import aprove.verification.oldframework.BasicStructures.*;
import aprove.verification.oldframework.Utility.GenericStructures.*;
import immutables.*;

public abstract class PredefinedFunctionsManager {

    /**
     * Maps an integer function symbol to the function symbol by which it is
     * replaced by this {@link PredefinedFunctionsManager}.
     */
    protected final Map<FunctionSymbol,FunctionSymbol> predefSymMap;

    /**
     * Additional rules generated by the transformation process.
     *
     * <p>These must be added to the transformed rule set to keep the transformation correct.</p>
     *
     * <p>Example: If the Term "0 + y" is converted to the pos-neg representation "plus(0, y)", this
     * set contains the rules for the function symbol plus.</p>
     */
    protected final Set<Rule> generatedRules;

    protected final IDPPredefinedMap idpPredefinedMap;

    protected PredefinedFunctionsManager(final IDPPredefinedMap predefinedMap) {
        this.idpPredefinedMap = predefinedMap;
        this.predefSymMap = new LinkedHashMap<FunctionSymbol, FunctionSymbol>();
        this.generatedRules = new LinkedHashSet<Rule>();
    }

    /**
     * Converts ITRS rules to ordinary TRS rules by replacing the implicitly
     * defined integer function symbols by explicitly defined function symbols
     * and rules (e.g. neg-pos or bit vectors).
     *
     * <p>Note: If <code>term</code> is a {@link TRSFunctionApplication}, so is
     * the return value.</p>
     *
     * @param t Term to convert

     * @return Converted term.
     */
    public TRSTerm extractTerm(TRSTerm t) throws IntOutOfRangeException {
        if (t.isVariable()) {
            return t;
        }

        t = this.normalizeNot(t, false);

        TRSFunctionApplication fApp = (TRSFunctionApplication) t;
        FunctionSymbol f = fApp.getRootSymbol();

        if (f.getArity() == 0) {

            final BigInteger intConstant = this.idpPredefinedMap.getInt(f, DomainFactory.INTEGERS);
            if (intConstant != null) {
                return this.numberToTerm(intConstant);
            }

        }
        if (this.hasRules(f)) {
            if (this.idpPredefinedMap.isAdd(f) || this.idpPredefinedMap.isMul(f)) {
                /* Special case for addition and multiplication: The rules for
                 * addition and multiplication work by deconstruction of the first
                 * argument. If the first argument is a ground term, we can do
                 * the addition/multiplication on the TRS level.
                 *
                 * So if we have f(s,t) where s is not a ground term, but t is
                 * a ground term, use f(t,s) instead. This is correct, as
                 * addition and multiplication are commutative.
                 */
                final List<? extends TRSTerm> args = fApp.getArguments();
                if (!args.get(0).getVariables().isEmpty() &&
                        args.get(1).getVariables().isEmpty()) {
                    fApp = TRSTerm.createFunctionApplication(f, args.get(1), args.get(0));
                }
            }
            final FunctionSymbol newF = this.substituteFunctionSymbol(f);
            f = newF;
        }
        final ImmutableList<? extends TRSTerm> args = fApp.getArguments();
        final List<TRSTerm> newArgs = new ArrayList<TRSTerm>(args.size());
        for (final TRSTerm arg : args) {
            newArgs.add(this.extractTerm(arg));
        }
        final TRSFunctionApplication newFApp = TRSTerm.createFunctionApplication(f, ImmutableCreator.create(newArgs));
        return newFApp;
    }

    /**
     * Substitutes a pre-defined function symbols by its new equivalent explicitly defined function
     * for which pre-defined rules will be added to the TRS.
     * @param f Function symbol to convert.
     * @return New function symbol.
     */
    public FunctionSymbol substituteFunctionSymbol(final FunctionSymbol f) {
        if (!this.hasRules(f)) {
            throw new IllegalArgumentException("function symbol has no rules");
        }
        FunctionSymbol newF = this.predefSymMap.get(f);
        if (newF == null) {
            final Pair<Set<Rule>,FunctionSymbol> pair = this.generateRules(f);
            this.generatedRules.addAll(pair.x);
            newF = pair.y;
            this.predefSymMap.put(f,newF);
        }
        return newF;
    }


    private TRSTerm normalizeNot(final TRSTerm t, final boolean negated) {
        if (t.isVariable()) {
            return t;
        }

        final TRSFunctionApplication fa = (TRSFunctionApplication) t;

        if (this.idpPredefinedMap.isLnot(fa.getRootSymbol())) {
            return this.normalizeNot(fa.getArgument(0), !negated);
        } else {
            FunctionSymbol newFaRoot = fa.getRootSymbol();

            if (negated) {
                final PredefinedFunction<?> semantics = this.idpPredefinedMap.getPredefinedFunction(fa.getRootSymbol());
                switch (semantics.getFunc()) {
                case Eq:
                    newFaRoot = this.idpPredefinedMap.getSym(Func.Neq, semantics.getDomains());
                    break;
                case Neq:
                    newFaRoot = this.idpPredefinedMap.getSym(Func.Eq, semantics.getDomains());
                    break;
                case Ge:
                    newFaRoot = this.idpPredefinedMap.getSym(Func.Lt, semantics.getDomains());
                    break;
                case Gt:
                    newFaRoot = this.idpPredefinedMap.getSym(Func.Le, semantics.getDomains());
                    break;
                case Le:
                    newFaRoot = this.idpPredefinedMap.getSym(Func.Gt, semantics.getDomains());
                    break;
                case Lt:
                    newFaRoot = this.idpPredefinedMap.getSym(Func.Ge, semantics.getDomains());
                    break;
                default: throw new UnsupportedOperationException("semantics not negateable: " + semantics);
                }
            }

            final ArrayList<TRSTerm> normalizedArgs = new ArrayList<TRSTerm>();
            for (final TRSTerm arg : fa.getArguments()) {
                normalizedArgs.add(this.normalizeNot(arg, false));
            }

            return TRSTerm.createFunctionApplication(newFaRoot, normalizedArgs);
        }

    }

    /**
     * Same as extractTerm(Term), just specialized for FunctionApplications.
     */
    public TRSFunctionApplication extractTerm(final TRSFunctionApplication fa)
            throws IntOutOfRangeException {
        return (TRSFunctionApplication)this.extractTerm((TRSTerm)fa);
    }

    /**
     * Return the additional rules generated by the transformation request.
     * These must be added to the resulting rule set to keep the
     * transformation correct.
     */
    public Set<Rule> getGeneratedRules() {
        return this.generatedRules;
    }

    /**
     * Maps an BigInteger to its Term representation.
     */
    protected abstract TRSFunctionApplication numberToTerm(BigInteger num)
            throws IntOutOfRangeException;

    /**
     * Checks if this is a function symbols which should be replaced by this
     * transformation.
     *<p>Default implementation just calls
     * {@link PredefinedFunctions}<code>.isPredefined()</code>.</p>
     *
     * <p>This should not be overridden at all - I cannot
     * think of a case where a predefined function symbol might stay
     * unchanged (and without rules) and the transformation is correct.
     * ({@link PredefinedManagerNegPos} uses this)
     * </p>
     */
    protected final boolean hasRules(final FunctionSymbol fs) {
        return this.idpPredefinedMap.isPredefined(fs);
    }

    /**
     * Returns the set of rules needed to calculate the function symbol's
     * semantic.
     *
     * <p>The default <code>extractTerm()</code> method caches the generated
     * value and takes care not to call this method again for the same
     * parameters. So the return value must stay constant over
     * the lifetime of an instance.</p>
     */
    protected abstract Pair<Set<Rule>, FunctionSymbol> generateRules(FunctionSymbol fs);

}
