package aprove.verification.oldframework.Haskell.Modules;

import java.util.*;

import aprove.verification.oldframework.Haskell.*;
import aprove.verification.oldframework.Haskell.BasicTerms.*;
import aprove.verification.oldframework.Haskell.Declarations.*;
import aprove.verification.oldframework.Haskell.Typing.*;
import aprove.verification.oldframework.Utility.*;

/**
 * @author Stephan Swiderski
 * @version $Id$
 *
 * This class represents a derived instance for a datatype (deriving statement)
 * it is always an instance of a class declared in prelude
 * it contains the constraintRule of the head directly
 * cause it is generated by the prelude (derive instances for)
 */

public class DerivedInstEntity extends InstEntity implements HaskellBean, EntityCollector{
    ClassConstraintRule constraintRule;

    /**
     * do not use this constructor, its only for bean convention
     */
    public DerivedInstEntity(){
        super();
    }

    /**
     * normal constructor
     */
    public DerivedInstEntity(String name,Module module,Set<HaskellEntity> ivarEntities,ClassConstraintRule constraintRule,TypeSchema inst){
        super(name,module,null,ivarEntities);
        this.setFixity(InfixDecl.FIXITY_DEFAULT);
        this.setPriority(InfixDecl.PRIORITY_DEFAULT);
        this.constraintRule = constraintRule;
        this.setType(inst);
    }

    @Override
    public HaskellObject visit(HaskellVisitor hv){
        hv.fcaseEntity(this);
        if (hv.guardEntity(this)) {
            if (hv.guardType(this)) {
                this.setType(this.walk(this.getType(),hv));
            }
            if (hv.guardMember(this)) {
                this.ivarEntities = this.listWalk(this.ivarEntities,hv);
            }
            if (hv.guardDerivedInstEntity(this)) {
                this.constraintRule = this.walk(this.constraintRule,hv);
            }
        }
        return hv.caseEntity(this);
    }

    @Override
    public Set<HaskellEntity> getSubEntities(){
        return this.ivarEntities;
    }

    @Override
    public ClassConstraintRule getConstraintRule(){
        return this.constraintRule;
    }

    /**
     * @returns the ClassConstraintRule of this instance head
     */
    public void setConstraintRule(ClassConstraintRule constraintRule){
        this.constraintRule = constraintRule;
    }

    /**
     * @returns the TyClassEntity this instance implements
     */
    @Override
    public HaskellEntity getTyClassEntity(){
        return this.constraintRule.getPattern().getTyClass().getEntity();
    }

    /**
     * @returns the TyConsEntity this instance implements
     */
    @Override
    public HaskellEntity getTyConsEntity(){
        Cons cons = (Cons) HaskellTools.getLeftMost(this.constraintRule.getPattern().getType());
        return cons.getSymbol().getEntity();
    }

    @Override
    public HaskellType getInstTypeTerm(){
        return this.constraintRule.getPattern().getType();
    }


    /**
     * the type is already set by the constructor, so no extra instantiate
     */
    @Override
    public void instantiate(){
    }

    @Override
    public Object deepcopy(){
        return this.hoCopy(new DerivedInstEntity(this.name,this.module,new HashSet<HaskellEntity>(this.ivarEntities),Copy.deep(this.constraintRule),Copy.deep((TypeSchema)this.getType())));
    }

}
