/*
 * Created on Feb 16, 2006
 */
package aprove.verification.dpframework.BasicStructures.Unification.Equational.Utility;

import java.util.*;

import aprove.verification.dpframework.BasicStructures.*;
import aprove.verification.dpframework.BasicStructures.Utility.*;

/** Substitution of constants with terms.
 *
 * @author Stephan Falke
 * @version $Id$
 */

public class ExtVarAbstraction {

    private  Map<ACnCTerm, TRSVariable> map;
    private  Map<TRSVariable, ACnCTerm> invMap;

    // ------------------- constructors

    private ExtVarAbstraction() {
        this.map = new LinkedHashMap<ACnCTerm, TRSVariable>();
        this.invMap = new LinkedHashMap<TRSVariable, ACnCTerm>();
    }

    /** Aliens of s are replaced by fresh variables that are generated by fvg.
     */
    public static ExtVarAbstraction create(ACnCTerm s, FreshVarGenerator fvg) {
        ExtVarAbstraction res = new ExtVarAbstraction();

        for(ACnCTerm t : s.getAliens()) {
            TRSVariable x = fvg.getFreshVariable(TRSTerm.createVariable("x"), false);
            res.put(t, x);
        }

        return res;
    }

    /** Extends this ExtVarAbstraction with the remaining aliens of s.
     */
    public void extend(ACnCTerm s, FreshVarGenerator fvg) {
        Set<ACnCTerm> dom = this.getDomain();

        for(ACnCTerm si : s.getAliens()) {
            if(!dom.contains(si)) {
                TRSVariable x = fvg.getFreshVariable(TRSTerm.createVariable("x"), false);
                this.put(si, x);
            }
        }
    }

    // ---------------- accessor methods

    /** Returns the variable the given term is mapped to by this substitution.
     * @param s  term whose mapping should be returned
     * @return Term that constant maps to
     */
    public TRSVariable get(ACnCTerm s) {
        return this.map.get(s);
    }

    public ACnCTerm invGet(TRSVariable x) {
        return this.invMap.get(x);
    }

    /** Adds a new abstraction.
     */
    public void put(ACnCTerm s, TRSVariable x) {
        this.map.put(s, x);
        this.invMap.put(x, s);
    }

    //------------- miscellaneous methods

    /** Conversion to a string representation.
     */
    @Override
    public String toString() {
        StringBuffer temp = new StringBuffer("[");
        for (Iterator i=this.map.keySet().iterator(); i.hasNext();) {
            ACnCTerm t = (ACnCTerm)i.next();
            temp.append(t.toString() + "/" + this.map.get(t).toString());
            if (i.hasNext()) {
                temp.append(", ");
            }
        }
        temp.append("]");
        return temp.toString();
    }

    @Override
    final public boolean equals(Object o) {
        ExtVarAbstraction s = (ExtVarAbstraction)o;
        return this.map.equals(s.map);
    }

    @Override
    final public int hashCode() {
        return this.map.hashCode();
    }

    public Set<ACnCTerm> getDomain() {
        return new LinkedHashSet<ACnCTerm>(this.map.keySet());
    }

    public Set<TRSVariable> getRange() {
        return new LinkedHashSet<TRSVariable>(this.invMap.keySet());
    }

}
