/*
 * Created on Feb 15, 2006
 */
package aprove.verification.dpframework.BasicStructures.Unification.Equational.Utility;

import java.util.*;

import aprove.verification.dpframework.BasicStructures.*;
import aprove.verification.dpframework.BasicStructures.Utility.*;

/** Substitution of constants with terms.
 *
 * @author Stephan Falke
 * @version $Id$
 */

public class VarAbstraction {

    private  Map<ACTerm, TRSVariable> map;
    private  Map<TRSVariable, ACTerm> invMap;

    // ------------------- constructors

    private VarAbstraction() {
        this.map = new LinkedHashMap<ACTerm, TRSVariable>();
        this.invMap = new LinkedHashMap<TRSVariable, ACTerm>();
    }

    /** Aliens of s are replaced by fresh variables that are generated by fvg.
     */
    public static VarAbstraction create(ACTerm s, FreshVarGenerator fvg) {
        VarAbstraction res = new VarAbstraction();

        for(ACTerm t : s.getAliens()) {
            TRSVariable x = fvg.getFreshVariable(TRSTerm.createVariable("x"), false);
            res.put(t, x);
        }

        return res;
    }

    /** Extends this VarAbstraction with the remaining aliens of s.
     */
    public void extend(ACTerm s, FreshVarGenerator fvg) {
        Set<ACTerm> dom = this.getDomain();

        for(ACTerm si : s.getAliens()) {
            if(!dom.contains(si)) {
                TRSVariable x = fvg.getFreshVariable(TRSTerm.createVariable("x"), false);
                this.put(si, x);
            }
        }
    }

    // ---------------- accessor methods

    /** Returns the variable the given term is mapped to by this substitution.
     * @param s  term whose mapping should be returned
     * @return Term that constant maps to
     */
    public TRSVariable get(ACTerm s) {
        return this.map.get(s);
    }

    public ACTerm invGet(TRSVariable x) {
        return this.invMap.get(x);
    }

    /** Adds a new abstraction.
     */
    public void put(ACTerm s, TRSVariable x) {
        this.map.put(s, x);
        this.invMap.put(x, s);
    }

    //------------- miscellaneous methods

    /** Conversion to a string representation.
     */
    @Override
    public String toString() {
        StringBuffer temp = new StringBuffer("[");
        for (Iterator i=this.map.keySet().iterator(); i.hasNext();) {
            ACTerm t = (ACTerm)i.next();
            temp.append(t.toString() + "/" + this.map.get(t).toString());
            if (i.hasNext()) {
                temp.append(", ");
            }
        }
        temp.append("]");
        return temp.toString();
    }

    @Override
    final public boolean equals(Object o) {
        VarAbstraction s = (VarAbstraction)o;
        return this.map.equals(s.map);
    }

    @Override
    final public int hashCode() {
        return this.map.hashCode();
    }

    public Set<ACTerm> getDomain() {
        return new LinkedHashSet<ACTerm>(this.map.keySet());
    }

    public Set<TRSVariable> getRange() {
        return new LinkedHashSet<TRSVariable>(this.invMap.keySet());
    }

}

