package aprove.solver.Engines;

import aprove.solver.*;
import aprove.strategies.Abortions.*;
import aprove.strategies.Annotations.*;
import aprove.verification.oldframework.PropositionalLogic.*;
import aprove.verification.oldframework.PropositionalLogic.SATCheckers.*;

public class MINISATEngine extends SatEngine {

    private final int version;

    // use SatELite style preprocessor to reduce CNF size?
    private final boolean simp;
    private final boolean assumps;

    // true:  use SAT4J's implementation of Tseitin's alg.
    // false: use external converter bc2sat
    private final boolean tseitin;
    private final boolean newDimacsGen;

    // when using XOR clauses, use light version of solver?
    private final boolean xorLight;

    // when using XOR clauses, use version of the solver with assertions?
    private final boolean xorAssert;

    @ParamsViaArgumentObject
    public MINISATEngine(Arguments arguments) {
        super(arguments);
        this.assumps = arguments.assumps;
        this.simp = arguments.simp;
        this.tseitin = arguments.tseitin;
        this.version = arguments.version;
        this.newDimacsGen = arguments.newDimacsGen;
        this.xorLight = arguments.xorLight;
        this.xorAssert = arguments.xorAssert;
    }

    @Override
    public SATChecker getSATChecker() {
        if (ExternalSpawner.isSupported()) {
            // TODO unify all those almost identical SATCheckers
            // apparently generated by copy & paste!
            return new MiniSATExtStartedFileChecker(this.version,
                    this.simp, this.assumps, this.tseitin, this.xorClauses);
        } else {
            if (this.version == 21) {
                // MiniSAT 2.1 became available by participating at
                // SAT Competition 2009
                String args = this.simp ? "" : "-no-pre";
                return new SATRaceStdinChecker("minisat21", args);
            }
            return new MiniSATFileChecker(this.version,
                    this.simp, this.assumps, this.tseitin, this.xorClauses,
                    this.xorLight, this.xorAssert, this.newDimacsGen,
                    false, false);
        }
    }

    public static class Arguments extends SatEngine.Arguments {
        public boolean assumps = false;
        public boolean simp = false;
        public boolean tseitin = true;
        public int version = 2;
        public boolean newDimacsGen = false;
        public boolean xorLight = false;
        public boolean xorAssert = true;
    }

}
