package aprove.verification.oldframework.PropositionalLogic.Translation;

import java.io.*;

/**
 * DimacsGenerator helps creating a dimacs file directly from FormulaTrees without
 * needing to do intermediate steps.
 * @author kabasci
 *
 */
public class DimacsGenerator {

    // Where the output goes
    private Writer out;
    private int nClauses = 0;
    private boolean hasFile = false;
    private File fileOut;
    private RandomAccessFile ra;

    /**
     * This is a generic constructor for DimacsGenerator. We only need any writer,
     * but the caller needs to ensure the head of the Dimacs file is attached in the right way.
     *
     * @param output A Writer where we write the output to.
     */
    public DimacsGenerator(final Writer output) {
        this.out = output;
    }

    /**
     * This is a more sophisticated constructor for the DimacsGenerator, which however is only useable if we use direct files, which can furthermore be opened in random access mode.
     * The file need not be open before this call. The advantage is that we do not have to worry about writing the prelude ourseles, and have a method to finish everything up.
     * The DimacsGenerator will keep track of the number of clauses. However since that info is simple to extract from the root and furthermore saves time the user will have to provide
     * the number of Variables, all of which need to have been used consecutively, and the maximum being the output of the master node, to the postprocessor.
     * @param outputFile The file to write to
     * @throws IOException
     */
    public DimacsGenerator(final File outputFile) throws IOException {
        this.hasFile = true;
        this.fileOut = outputFile;
        this.out = new FileWriter(this.fileOut);
        this.out.write("c Generated by AProVE\n");
        // This will later contain the number of clauses and variable.
        // To this time, these numbers are not known.
        // One billion of those are enough for time being, it is not sure that all solvers can handle more.
        this.out.write("p cnf                      \n");
    }

    /**
     * Helper method to reopen the stream readonly.
     */
    private synchronized void reOpenRA() throws IOException {
        this.out.flush();
        this.out.close();
        this.out = null;
        this.ra = new RandomAccessFile(this.fileOut, "rws");
    }


    /**
     * Finishes up the writing if we had a file to start with. If we had a writer, throws an IOException.
     * @param numVars
     * @throws IOException
     */
    public void postProcess(final int numVars) throws IOException {
      // Is this call valid?
      if (!this.hasFile) {
          throw new IOException("This DimacsGenerator has not been given a file and cannot do postprocessing by itself, or it has already been done.");
      }

      // This can be done only once.
      this.hasFile = false;

      // Ok, let us close the prior writing module, and reopen a random access file descriptor for it.
      // To avoid any races, let's synchronize this.
      this.reOpenRA();

      // From now on, all calls to other writing methods of this class automatically fail due to a lack of a stream to write to.

      // Seek to the position where we want to have the number of vars.
      this.ra.seek(28);
      this.ra.writeBytes(Integer.toString(numVars));
      // ... and the number of clauses.
      this.ra.seek(39);
      this.ra.writeBytes(Integer.toString(this.nClauses));
      this.ra.close();

    }

    /**
     * writes a clause given by literals to the dimacs.
     * We will only use this for short clauses, see one method below
     * for the one for bigger clauses.
     * @param clause The clause to add, given as an array of ints
     */
    public void outputClause(final int... clause) throws IOException {
        Writer out = this.out; // minor speedup
        for (final int element : clause) {
            out.write(Integer.toString(element));
            out.write(" ");
        }
        out.write("0\n");
        this.nClauses++;
        //// Once in a while, flush for better performance.
        //if (this.nClauses % 1000 == 0) {
        //    this.out.flush();
        //}
    }

    /**
     * writes a clause given by literals to the dimacs.
     * This one is for bigger clauses, so we can reuse the array.
     * @param clause The clause to add, given as an array of ints
     * @param count The number of literals to regard
     */
    public void outputClause(final int[] clause, final int count) throws IOException {

        Writer out = this.out; // minor speedup
        for (int i=0; i<count; i++) {
            out.write(Integer.toString(clause[i]));
            out.write(" ");
        }
        out.write("0\n");
        this.nClauses++;
        //// Once in a while, flush for better performance.
        //if (this.nClauses % 1000 == 0) {
        //    this.out.flush();
        //}
    }

}
