# Properties for GUI with HandlingMode Termination
# Properties for TypedInputs with HandlingMode Termination
TES = aprove.Auto.current
TRS = aprove.Auto.current
XTC = aprove.Auto.current
HASKELL = aprove.Auto.current
ETES = aprove.Auto.current
ETRS = aprove.Auto.current
SES = aprove.Auto.current
SRS = aprove.Auto.current
QDP = aprove.Auto.current
QTRS = aprove.Auto.current
RTRS = aprove.Auto.current
GTRS = aprove.Auto.current
OTRS = aprove.Auto.OTRSAuto
CSR = aprove.Auto.CSR
PROLOG = aprove.Auto.current
NEWPROLOG = aprove.Auto.current
PATRS = aprove.Auto.current
CSPATRS = aprove.Auto.current
CLS = aprove.Auto.current
IPAD = aprove.Auto.IPADAuto
FP = aprove.Auto.FPAuto
ITRS = aprove.Auto.current
IDP = aprove.Auto.current
JBC = aprove.Auto.current
LLVM = aprove.Auto.current
CTRS = aprove.Auto.current
TRIPLES = aprove.Auto.current
MCS = aprove.Auto.current
T2 = aprove.Auto.current
INTTRS = aprove.Auto.current
C = aprove.Auto.current
PTRS = aprove.Auto.current