package aprove.verification.oldframework.Bytecode.Parser;

/**
 * Some constants used in class file parsing.
 *
 * @author Marc Brockschmidt
 */
public final class ClassFileParserConstants {
    /** Pseudo-constructor, to avoid instantiation. */
    private ClassFileParserConstants() {
        throw new UnsupportedOperationException();
    }

    /** Magic number at the beginning of each valid class file. */
    public static final int CLASS_FILE_MAGIC_NUMBER = 0xCAFEBABE;

    /**************************************************************************
     *************************** Constant pool tags ***************************
     **************************************************************************/
    /** The tag used to mark constant pool entries as containing a UTF8-encoded string */
    public static final int CONSTANT_POOL_UTF8_TAG = 1;

    /** The tag used to mark constant pool entries containing a big-endian integer. */
    public static final int CONSTANT_POOL_INTEGER_TAG = 3;

    /** The tag used to mark constant pool entries containing a IEEE754 floating point number */
    public static final int CONSTANT_POOL_FLOAT_TAG = 4;

    /** The tag used to mark constant pool entries containing a 8 byte long big-endian
     *  integral number. */
    public static final int CONSTANT_POOL_LONG_TAG = 5;

    /** The tag used to mark constant pool entries containing a IEEE754 double-precision
     *  floating point number */
    public static final int CONSTANT_POOL_DOUBLE_TAG = 6;

    /** The tag used to mark constant pool entries containing a constant pool reference
     *  to a raw UTF8 string representing a fully qualified class or interface name.  */
    public static final int CONSTANT_POOL_CLASS_REF_TAG = 7;

    /** The tag used to mark constant pool entries containing a constant pool reference
     *  to a raw UTF8 string that will be used to create a java.lang.String object. */
    public static final int CONSTANT_POOL_STRING_REF_TAG = 8;

    /** The tag used to mark constant pool entries containing a constant pool reference
     *  to a class reference entry (for class or interface C) and a reference to a name
     *  and type information entry, fully describing a field member of C. */
    public static final int CONSTANT_POOL_FIELD_REF_TAG = 9;

    /** The tag used to mark constant pool entries containing a constant pool reference
     *  to a class reference entry (for class C) and a reference to a name and type
     *  information entry, fully describing a method member of C. */
    public static final int CONSTANT_POOL_METHOD_REF_TAG = 10;

    /** The tag used to mark constant pool entries containing a constant pool reference
     *  to a class reference entry (for interface I) and a reference to a name and type
     *  information entry, fully describing a method member of I. */
    public static final int CONSTANT_POOL_INTERFACE_METHOD_REF_TAG = 11;

    /** The tag used to mark constant pool entries containing a constant pool reference
     *  to a raw UTF8 string representing an unqualified method name (or "&lt;init&gt;")
     *  and a constant pool reference to a raw UTF8 string representing a field or method
     *  descriptor. */
    public static final int CONSTANT_POOL_NAME_AND_TYPE_REF_TAG = 12;

    public static final int CONSTANT_POOL_METHOD_HANDLE = 15;
    public static final int CONSTANT_POOL_METHOD_TYPE = 16;
    public static final int CONSTANT_POOL_INVOKE_DYNAMIC = 18;

    /**************************************************************************
     *************************** Class Access Flags ***************************
     **************************************************************************/
    /** Used for classes declared as <code>public</code>. */
    public static final int CLASS_ACCESS_FLAG_PUBLIC = 0x0001;

    /** Used for classes declared as <code>final</code>. */
    public static final int CLASS_ACCESS_FLAG_FINAL = 0x0010;

    /** Marks that superclass methods invoked by invokespecial need to be
     *  handled ... special. */
    public static final int CLASS_ACCESS_FLAG_SUPER = 0x0020;

    /** Used to mark that a class file describes an interface. */
    public static final int CLASS_ACCESS_FLAG_INTERFACE = 0x0200;

    /** Used for classes declared as <code>abstract</code>. */
    public static final int CLASS_ACCESS_FLAG_ABSTRACT = 0x0400;

    /** Used for classes declared as <code>synthetic</code> (== were
     *  generated by the compiler). */
    public static final int CLASS_ACCESS_FLAG_SYNTHETIC = 0x1000;

    /** Used for classes declared as <code>Annotation</code>. */
    public static final int CLASS_ACCESS_FLAG_ANNOTATION = 0x2000;

    /** Used for classes declared as <code>enum</code>. */
    public static final int CLASS_ACCESS_FLAG_ENUM = 0x4000;

    /**************************************************************************
     *************************** Field Access Flags ***************************
     **************************************************************************/
    /** Used for fields declared as <code>public</code>. */
    public static final int FIELD_ACCESS_FLAG_PUBLIC = 0x0001;

    /** Used for fields declared as <code>private</code>. */
    public static final int FIELD_ACCESS_FLAG_PRIVATE = 0x0002;

    /** Used for fields declared as <code>protected</code>. */
    public static final int FIELD_ACCESS_FLAG_PROTECTED = 0x0004;

    /** Used for fields declared as <code>static</code>. */
    public static final int FIELD_ACCESS_FLAG_STATIC = 0x0008;

    /** Used for fields declared as <code>final</code>. */
    public static final int FIELD_ACCESS_FLAG_FINAL = 0x0010;

    /** Used for fields declared as <code>volatile</code>. */
    public static final int FIELD_ACCESS_FLAG_VOLATILE = 0x0040;

    /** Used for fields declared as <code>transient</code>. */
    public static final int FIELD_ACCESS_FLAG_TRANSIENT = 0x0080;

    /** Used for fields declared as <code>synthetic</code> (== were
     *  generated by the compiler). */
    public static final int FIELD_ACCESS_FLAG_SYNTHETIC = 0x1000;

    /** Used for fields declared as element of an <code>enum</code>. */
    public static final int FIELD_ACCESS_FLAG_ENUM = 0x4000;

    /**************************************************************************
     ************************** Method Access Flags ***************************
     **************************************************************************/
    /** Used for methods declared as <code>public</code>. */
    public static final int METHOD_ACCESS_FLAG_PUBLIC = 0x0001;

    /** Used for methods declared as <code>private</code>. */
    public static final int METHOD_ACCESS_FLAG_PRIVATE = 0x0002;

    /** Used for methods declared as <code>protected</code>. */
    public static final int METHOD_ACCESS_FLAG_PROTECTED = 0x0004;

    /** Used for methods declared as <code>static</code>. */
    public static final int METHOD_ACCESS_FLAG_STATIC = 0x0008;

    /** Used for methods declared as <code>final</code>. */
    public static final int METHOD_ACCESS_FLAG_FINAL = 0x0010;

    /** Used for methods declared as <code>synchronized</code>. */
    public static final int METHOD_ACCESS_FLAG_SYNCHRONIZED = 0x0020;

    /** Used for bridge methods (generated by the compiler) */
    public static final int METHOD_ACCESS_FLAG_BRIDGE = 0x0040;

    /** Used for methods declared with a variable number of arguments. */
    public static final int METHOD_ACCESS_FLAG_VARAGS = 0x0080;

    /** Used for methods declared as <code>native</code> */
    public static final int METHOD_ACCESS_FLAG_NATIVE = 0x0100;

    /** Used for methods declared as <code>abstract</code>. */
    public static final int METHOD_ACCESS_FLAG_ABSTRACT = 0x0400;

    /** Used for methods declared as <code>strictfp</code>. */
    public static final int METHOD_ACCESS_FLAG_STRICT = 0x0800;

    /** Used for methods declared as <code>synthetic</code> (== were
     *  generated by the compiler). */
    public static final int METHOD_ACCESS_FLAG_SYNTHETIC = 0x1000;
}
