package aprove.verification.oldframework.Algebra.Polynomials;

import java.math.*;
import java.util.*;

/**
 * Some helpers to build DC Patterns
 *
 *
 * @author Patrick Kabasci
 * @version $Id$
 */
public class DioConstraintPatterns {
    private static int freshNum= 0;


    /**
     * docu-guess (fuhs):
     * Must not be called with polynomials containing a variable name that starts
     * with "gt_" that has not been generated by this class.
     *
     * @param gt
     * @param cArgs
     * @param name
     * @return
     */
    public static IndefinitePart encodeIfGe(SimplePolynomial gt, List<SimplePolyConstraint> cArgs, String name)  {

        IndefinitePart res = IndefinitePart.create("gt_" + Integer.toString(DioConstraintPatterns.freshNum) + name, 1);
        DioConstraintPatterns.freshNum++;
        cArgs.add(new SimplePolyConstraint( gt.times(res), ConstraintType.GE));
        SimplePolynomial indefPol = SimplePolynomial.create(res, BigInteger.ONE);
        cArgs.add(new SimplePolyConstraint (SimplePolynomial.ONE.minus(indefPol), ConstraintType.GE));

        return res;
    }
}

