package aprove.verification.oldframework.Bytecode.Processors.ToMethodSummary;

import static aprove.verification.oldframework.Input.HandlingMode.*;

import java.io.*;
import java.util.*;

import aprove.verification.oldframework.Algebra.Polynomials.*;
import aprove.verification.oldframework.Bytecode.Natives.*;
import aprove.verification.oldframework.Bytecode.Natives.MethodSummary.*;
import aprove.verification.oldframework.Bytecode.Parser.*;
import aprove.verification.oldframework.Bytecode.Processors.ToComplexity.*;
import aprove.verification.oldframework.Bytecode.Utils.MethodSummary.*;
import aprove.verification.oldframework.Input.*;

public class MethodSummaryBuilder {
    private Set<String> modifies;
    private List<Task> tasks;
    private IMethod method;
    private SimplePolynomial lowerTime, upperTime, lowerSpace, upperSpace;
    private SizeBounds sizeBounds;
    private String filename;
    private Map<Task, Exception> errors;

    public MethodSummaryBuilder(IMethod method, Set<Integer> changedArgs, boolean changedEnv, String filename) {
        this.method = method;
        this.filename = filename;
        this.sizeBounds = new SizeBounds();
        this.errors = new LinkedHashMap<>();
        computeTasks(changedArgs, changedEnv);
    }

    private void computeTasks (Set<Integer> changedArgs, boolean changedEnv) {
        modifies = new LinkedHashSet<>();
        tasks = new LinkedList<>();

        //time & space
        tasks.add(new Task(RuntimeComplexity, null));
        tasks.add(new Task(SpaceComplexity, null));

        //ret
        if (method.getDescriptor().getReturnType() != null) {
            tasks.add(new Task(SizeComplexity, ComplexityGoalTerm.RET));
        }

        //this & args
        for (Integer arg : changedArgs) {
            int index = arg;
            if (index == 0 && !method.isStatic()) {
                Task task = new Task(SizeComplexity, ComplexityGoalTerm.THIS);
                tasks.add(task);
                modifies.add(task.goalTerm.toString());
            } else {
                if (!method.isStatic()) {
                    index--; //account for "this", so local variable at pos 1 becomes arg0
                }
                Task task = new Task(SizeComplexity, ComplexityGoalTerm.arg(index));
                tasks.add(task);
                modifies.add(task.goalTerm.toString());
            }
        }

        //env
        if (changedEnv) {
            Task task = new Task(SizeComplexity, ComplexityGoalTerm.ENV);
            tasks.add(task);
            modifies.add(task.goalTerm.toString());
        }
    }

    public void setLowerTime(SimplePolynomial lowerTime) {
        this.lowerTime = lowerTime;
    }
    public void setUpperTime(SimplePolynomial upperTime) {
        this.upperTime = upperTime;
    }
    public void setLowerSpace(SimplePolynomial lowerSpace) {
        this.lowerSpace = lowerSpace;
    }
    public void setUpperSpace(SimplePolynomial upperSpace) {
        this.upperSpace = upperSpace;
    }

    public synchronized void addLowerBound(String key, SimplePolynomial bound) {
        sizeBounds.addLowerBound(key, bound);
    }
    public synchronized void addUpperBound(String key, SimplePolynomial bound) {
        sizeBounds.addUpperBound(key, bound);
    }

    protected synchronized void endTask (Task task) {
        assert tasks.contains(task);
        tasks.remove(task);
        if (isFinished()) {
            printSummary();
        }
    }

    public synchronized boolean isFinished() {
        return tasks.isEmpty();
    }

    public List<Task> getTasks() {
        return tasks;
    }

    public Map<Task, Exception> getErrors() {
        return errors;
    }

    public MethodSummary createMethodSummary() {
        ComplexitySummary complexity = new ComplexitySummary(lowerTime, upperTime, lowerSpace, upperSpace, sizeBounds, modifies);
        return new MethodSummary(method.isStatic(), complexity, method.getMethodIdentifier());
    }

    public MethodSummary printSummary() {
        MethodSummary summary = createMethodSummary();
        List<String> comments = new LinkedList<>();
        comments.add("Summary autmatically generated by AProVE");
        errors.forEach((task, e) -> comments.add("Error in " + task + ": " + e));
        String out = summary.toString(comments);

        if (filename == null) {
            System.out.println(out);
            return summary;
        }

        final File path = new File(filename);
        FileWriter fw = null;
        try {
            fw = new FileWriter(path);
            fw.append(out);
            System.out.println("Method Summary written to " + path.getPath());
        } catch (final IOException e) {
            System.err.println("Could not write output, aborting: " + e.getMessage());
            System.exit(1);
        } finally {
            if (fw != null) {
                try {
                    fw.close();
                } catch (final IOException e) {
                    System.err.println("Could not write output, aborting: " + e.getMessage());
                    System.exit(1);
                }
            }
        }
        return summary;
    }

    public class Task {

        private final HandlingMode goal;
        private final ComplexityGoalTerm goalTerm;

        public Task(HandlingMode goal, ComplexityGoalTerm goalTerm) {
            this.goal = goal;
            this.goalTerm = goalTerm;
        }

        public HandlingMode getGoal() {
            return goal;
        }

        public ComplexityGoalTerm getGoalTerm() {
            return goalTerm;
        }

        public void finish (SimplePolynomial size) {
            synchronized (MethodSummaryBuilder.this) {
                switch (goal) {
                case RuntimeComplexity:
                    setUpperTime(size);
                    break;
                case SpaceComplexity:
                    setUpperSpace(size);
                    break;
                case SizeComplexity:
                    addUpperBound(goalTerm.getStringRepresentation(), size);
                    break;
                }
                endTask(this);
            }
        }

        public void fail (Exception e) {
            synchronized (MethodSummaryBuilder.this) {
                switch (goal) {
                case RuntimeComplexity:
                case SpaceComplexity:
                    if (e instanceof RuntimeException) {
                        throw (RuntimeException)e;
                    } else {
                        throw new RuntimeException(e);
                    }
                case SizeComplexity:
                    errors.put(this,e);
                    endTask(this);
                }
            }
        }

        public MethodSummaryBuilder getBuilder() {
            return MethodSummaryBuilder.this;
        }

        @Override
        public String toString() {
            return "Task [goal=" + goal + (goalTerm != null ? ", goalTerm=" + goalTerm : "") + "]";
        }


    }

}
