DEFAULT = aprove.input.Programs.tes.Translator
fp = aprove.input.Programs.fp.Translator
sfp = aprove.input.Programs.fp.Translator
#fp = aprove.input.Programs.haskell.Translator
tes = aprove.input.Programs.tes.Translator
trs = aprove.input.Programs.newTrs.Translator
ptrs = aprove.input.Programs.newPtrs.Translator
ari = aprove.input.Programs.ariTrs.Translator
xtrs = aprove.input.Programs.newTrs.Translator
ses = aprove.input.Programs.srs.Translator
xsrs = aprove.input.Programs.xsrs.Translator
pl = aprove.input.Programs.prolog.Translator
npl = aprove.input.Programs.prolog.Translator
ttt = aprove.input.Programs.ttt.Translator
idp = aprove.input.Programs.newIDP.Translator
cint = aprove.input.Programs.cint.Translator
koat = aprove.input.Programs.cint.Translator
itrs = aprove.input.Programs.itrs.Translator
ipad = aprove.input.Programs.ipad.Translator
hs = aprove.input.Programs.haskell.Translator
srs = aprove.input.Programs.srs2.Translator
qdp = aprove.input.Programs.newTrs.Translator
qtrs = aprove.input.Programs.newTrs.Translator
strs = aprove.input.Programs.strs.Translator
patrs = aprove.input.Programs.patrs.Translator
cls = aprove.input.Programs.cls.Translator
class = aprove.input.Programs.jbc.Translator
jar = aprove.input.Programs.jbc.Translator
dio = aprove.input.Diophantine.Translator
triples = aprove.input.Programs.triples.Translator
xml = aprove.input.Programs.xtc.Translator
xtc = aprove.input.Programs.xtc.Translator
obl = aprove.input.Programs.newTrs.Translator
mc = aprove.input.Programs.mcs.Translator
mc2 = aprove.input.Programs.mcs.Translator
mcs = aprove.input.Programs.mcs.Translator
llvm = aprove.input.Programs.llvm.Translator
ll = aprove.input.Programs.llvm.Translator
t2 = aprove.input.Programs.t2.Translator
inttrs= aprove.input.Programs.intTrs.Translator
c = aprove.input.Programs.c.Translator
cpp = aprove.input.Programs.c.Translator
i = aprove.input.Programs.c.Translator
intc = aprove.input.Programs.intProg.Translator
