/* This file was generated by SableCC (http://www.sablecc.org/). */

package aprove.input.Programs.haskell;

import java.io.*;
import java.util.*;

import aprove.input.Generated.haskell.lexer.*;
import aprove.input.Generated.haskell.node.*;
import aprove.verification.oldframework.Utility.GenericStructures.*;

public class LayoutLexer extends aprove.input.Generated.haskell.lexer.Lexer {

    /**
     * stores the found start terms
     */
    public List<Pair<Token,String>> startterms = new ArrayList<Pair<Token,String>>();

    protected static final int START = 0;
    protected static final int MODULE = 1;
    protected static final int EXIST = 2;
    protected static final int EXISTLET = 3;
    protected static final int EXISTWHERE = 4;
    protected static final int EXISTOF = 5;
    protected static final int EXISTDO = 6;

    protected static final int NORMAL = 10;
    protected static final int LET = LayoutLexer.EXISTLET+LayoutLexer.NORMAL;
    protected static final int WHERE = LayoutLexer.EXISTWHERE+LayoutLexer.NORMAL;
    protected static final int OF = LayoutLexer.EXISTOF+LayoutLexer.NORMAL;
    protected static final int DO = LayoutLexer.EXISTDO+LayoutLexer.NORMAL;
    protected static final int DIRECT_CLOSE = LayoutLexer.NORMAL+LayoutLexer.NORMAL;

    protected Vector<Token> tokenFIFO;
    protected Stack<Indent> indents;
    protected int curLine;
    protected Token laytoken;
    protected Token lookahead;
    protected Token retoken;
    protected int tabadd;
    protected int oldLine;
    protected int comments;
    public boolean show = true;
    protected boolean change;

    public LayoutLexer(PushbackReader in) throws IOException, LexerException {
        super(in);
        this.change = false;
        this.comments = 0;
        this.tabadd = 0;
        this.oldLine = -1;
        this.curLine = -1;
        this.lookahead = null;
        this.retoken = null;
        this.indents = new Stack<Indent>();
        this.nextLAToken();
        this.indents.push(new Indent(LayoutLexer.START,-1,-1,false));
        int niPos = this.lookahead.getPos();
        int niLine = this.lookahead.getLine();

        if (this.lookahead instanceof TKwmainmodule){
           this.laytoken = this.getToken();
        } else if (this.lookahead instanceof TKwterm){
           this.laytoken = this.getToken();
        } else if ((this.lookahead instanceof TKwmodule)){
           this.laytoken = this.getToken();
        } else {
           this.openExIndent(new Indent(LayoutLexer.MODULE,niLine,niPos,true));
           this.laytoken = new TWopen(0,0);
        }
    }

    protected void myFilter() throws LexerException, IOException {
//        System.err.println(token.getText()+" : "+this.state.id()+","+token.getLine()+","+token.getPos()+","+token.getClass().getName());

        if (this.token instanceof TStartterm) {
            String text = this.token.getText();
            this.startterms.add(new Pair<Token,String>(this.token, text));
            this.token = null;
            return;
        }
        if ((this.token instanceof TStarttermBegin) ||
            (this.token instanceof TStarttermEnd)) {
            this.token = null;
            return;
        }

        if ((this.token instanceof TComment) ||
            (this.token instanceof TNewline) ||
            (this.token instanceof TLcomment) ||
            (this.token instanceof TLinecomment) ||
            (this.token instanceof TComment)  ||
            (this.token instanceof TBlanks) ){
           this.token = null;
           return;
        }
        if (this.token instanceof TCopen){
           this.comments++;
           this.token = null;
           return;
        }
        if (this.token instanceof TCclose){
           if (this.comments >0) {
            this.comments--;
        }
           if (this.comments == 0) {
            this.state = State.NORMAL;
        }
           this.token = null;
           return;
        }
        if (this.token.getLine() != this.oldLine){
            this.oldLine = this.token.getLine();
            this.tabadd = 0;
        }
        if (this.token instanceof TTab){
            int e = (this.token.getPos()+this.tabadd-1) & 7;
            this.tabadd = this.tabadd + 7 - e;
            this.token = null;
            return;
        } else {
            this.token.setPos(this.token.getPos()+this.tabadd);
        }
    }

    protected Token nextToken() throws IOException, LexerException {
        this.token = null;
        while (this.token == null) {
           this.token = super.getToken();
           this.myFilter();
        }
        return this.token;
    }

    protected Token nextLAToken() throws IOException, LexerException {
        Token res = this.lookahead;
        this.lookahead = this.nextToken();
        int flag = -1;
        if (res instanceof TKwwhere) { flag = LayoutLexer.WHERE; }
        else if (res instanceof TKwdo) { flag = LayoutLexer.DO;
            if (!(this.lookahead instanceof TWopen)) {
           return new OpenToken(res,this.lookahead,flag);
            }
        return res;
    }
        else if (res instanceof TKwof) { flag = LayoutLexer.OF; }
        else if (res instanceof TKwlet) { flag = LayoutLexer.LET; }
        if (flag > -1 && !(this.lookahead instanceof TWopen)) {
            this.lookahead = new OpenToken(this.lookahead,flag);
        }
        return res;
    }

    protected Indent peekIndent(){
        return this.indents.peek();
    }

    protected void openExIndent(Indent indent){
        this.change = true;
        this.indents.push(indent);
    }

    protected int closeExIndent(){
        this.change = true;
        //if (this.indents.size()==1) throw new RuntimeException("dddssss");
        return this.indents.pop().getFlag();
    }

    protected Token test(Token t) throws IOException, LexerException {
        this.retoken = null;
        this.change = false;
        if (t instanceof EOF) {
           if (this.peekIndent().getFlag() > LayoutLexer.START) {
              this.closeExIndent();
              this.retoken = t;
              return new TWclose(this.curLine,0);
           }
           return t;
        }
        if (t instanceof TKwmodule) {
           if (this.peekIndent().getFlag() > LayoutLexer.START) {
              this.closeExIndent();
              this.retoken = t;
              return new TWclose(this.curLine,0);
           }
           return t;
        }
    if (t instanceof MyTWopen){
            int niPos = t.getPos();
            int niLine = t.getLine();
            boolean seps = true;
            if (niPos <= this.peekIndent().getPos()) {
                niPos = this.peekIndent().getPos()+1;
                seps = false;
            }
            this.openExIndent(new Indent(LayoutLexer.DO,niLine,niPos,seps));
        return ((MyTWopen)t).toTWopen();
    }

    if (t instanceof OpenToken) {
            OpenToken ot = (OpenToken) t;
            if (ot.getSToken()!= null) {
           int niPos = ot.getSToken().getPos();
               int niLine = ot.getSToken().getLine();
             this.retoken = new MyTWopen(niLine,niPos);
               return ot.getToken();
        } else {


             this.retoken = ot.getToken();
               int flag = ot.getFlag();
               int niPos = this.retoken.getPos();
               int niLine = this.retoken.getLine();
               boolean seps = true;
               if (niPos <= this.peekIndent().getPos()) {
                  niPos = this.peekIndent().getPos()+1;
                  seps = false;
               }
               this.openExIndent(new Indent(flag,niLine,niPos,seps));

               return new TWopen(niLine,niPos);
        }
        }
    if ((t instanceof TKwin) && (t.getPos() == this.peekIndent().getPos())) {
            this.closeExIndent();
            this.retoken = t;
            return new TWclose(t.getLine(),t.getPos());
    }
        if (t.getPos() < this.peekIndent().getPos()) {
            this.closeExIndent();
            this.retoken = t;
            return new TWclose(t.getLine(),t.getPos());
        } else if (this.peekIndent().getSeps()) {
            if (t.getLine() > this.curLine) {
                this.curLine = t.getLine();
                if (t.getLine() != this.peekIndent().getLine()) {
                   if (t.getPos() == this.peekIndent().getPos()){
                      if ((t instanceof TWsep) || (t instanceof TWclose)) {
                          return t;
                      } else {
                          this.retoken = t;
                          return new TWsep(this.curLine,0);
                      }
                   }
                }
            }
        }
        if (t instanceof TWclose) {
            if (this.closeExIndent() != LayoutLexer.EXIST) {

            }
            return t;
        }

        if (t instanceof TWopen) {
           this.openExIndent(new Indent(LayoutLexer.EXIST,-1,-1,true));
           return t;
        }
        return t;
    }

    @Override
    public Token peek() throws LexerException, IOException {
        return this.laytoken;
    }

    @Override
    public Token next() throws IOException, LexerException {
        Token res = this.laytoken;
        this.laytoken = this.getToken();
        if ((res instanceof TWopen) || (res instanceof TWsep)) {
           while (this.laytoken instanceof TWsep){
              this.laytoken = this.getToken();
            }
        }
        //System.err.println(res.getText()+" : "+res.getClass().getName());
        return res;
    }

    public boolean insertMissing(){
        if (this.change) {
            return false;
        }
        if (aprove.Globals.DEBUG_SWISTE || aprove.Globals.DEBUG_MATRAF) {
            System.err.println("laytoken:"+this.laytoken);
            System.err.println("retoken:"+this.retoken);
        }
        this.retoken = this.laytoken;
        this.laytoken = new TWclose(this.curLine,0);
        if (aprove.Globals.DEBUG_SWISTE || aprove.Globals.DEBUG_MATRAF) {
            System.err.println("laytoken:"+this.laytoken);
            System.err.println("retoken:"+this.retoken);
        }
        this.closeExIndent();
        return true;
    }


    @Override
    public Token getToken() throws IOException, LexerException {
        if (this.retoken == null) {
            this.retoken = this.nextLAToken();
        }
        Token tok = this.test(this.retoken);
        //System.err.println(tok.getText()+" : "+tok.getClass().getName());
    return tok;
    }

    protected static class MyTWopen extends Token {
        public MyTWopen(int line, int pos){
            this.setLine(line);
        this.setPos(pos);
        }

        public Token toTWopen(){
            return new TWopen(this.getLine(),this.getPos());
        }

    @Override
    public Object clone(){
        return null;
    }

    @Override
    public void apply(Switch sw){
        }
   }

    protected static class OpenToken extends Token {
         protected Token token,sToken;
         protected int flag;

         public OpenToken(Token token, int flag){
             this.flag = flag;
             this.token = token;
         this.sToken = null;
         }

     public OpenToken(Token token,Token sToken, int flag){
             this.flag = flag;
             this.token = token;
         this.sToken = sToken;
         }

         public int getFlag(){
             return this.flag;
         }

         public Token getToken(){
             return this.token;
         }

     public Token getSToken(){
             return this.sToken;
         }

         @Override
        public Object clone(){
             return new OpenToken(this.token,this.sToken,this.flag);
         }

         @Override
        public void apply(Switch sw){
         }
    }

    protected static class Indent {

         protected int flag;
         protected int line;
         protected int pos;
         protected boolean seps;

         public Indent(int flag,int line,int pos,boolean seps){
             this.flag = flag;
             this.pos = pos;
             this.line = line;
             this.seps = seps;
         }

         public int getFlag(){
             return this.flag;
         }

         public int getPos(){
             return this.pos;
         }

         public int getLine(){
             return this.line;
         }

         public boolean getSeps(){
             return this.seps;
         }
    }
}

