TES = aprove.verification.oldframework.Input.Annotators.TESAnnotator
SES = aprove.verification.oldframework.Input.Annotators.SESAnnotator
PROLOG = aprove.verification.oldframework.Input.Annotators.PrologAnnotator
HASKELL = aprove.verification.oldframework.Input.Annotators.HaskellAnnotator
TheoremProver = aprove.verification.oldframework.Input.Annotators.TheoremProverAnnotator
JBC = aprove.verification.oldframework.Input.Annotators.JBCAnnotator
