package aprove.verification.oldframework.PropositionalLogic.Formulae;

import java.util.*;

import aprove.*;
import aprove.verification.oldframework.PropositionalLogic.*;

/**
 * Builds formulae. Caches each formula ever generated by this such
 * that we will automatically achieve formula sharing (circuit
 * sharing actually, since shared formulae == circuits).
 *
 * This class contains lots of code redundancies with
 * FullSharingFlatteningFactory.
 *
 * @author Peter Schneider-Kamp, Carsten Fuhs
 * @version $Id$
 */
public class CountingFullSharingFlatteningFactory<T> extends AbstractCountingCircuitFactory<T> {

    public CountingFullSharingFlatteningFactory(int limit) {
        super(limit);
    }


    @Override
    public <U> FormulaFactory<U> toTheory() {
        return new CountingFullSharingFlatteningFactory<U>(this.limit);
    }

    @Override

    public Formula<T> buildAnd(List<? extends Formula<T>> fmlae) {
        switch (fmlae.size()) {
        case 0:
            return this.ONE;
        case 1:
            return fmlae.get(0);
        default:
            // only necessary to check the elements of fmlae since
            // AndFormula.args.get(k) instanceof AndFormula cannot occur
            Set<Formula<T>> argsSet = new LinkedHashSet<Formula<T>>((fmlae.size()*11)/10);
            for (Formula<T> formula : fmlae) {
                if (formula == this.ZERO) {
                    return formula;
                }
                if (formula == this.ONE) {
                    continue;
                }
                if (formula instanceof AndFormula) {
                    AndFormula<T> andFormula = (AndFormula<T>) formula;
                    argsSet.addAll(andFormula.args);
                } else {
                    argsSet.add(formula);
                }
            }
            List<Formula<T>> args = new ArrayList<Formula<T>>(argsSet);
            switch (args.size()) {
            case 0:
                return this.ONE;
            case 1:
                return args.get(0);
            default:
                Formula<T> res = this.ANDS.get(argsSet);
                if (Globals.DEBUG_FUHS) {
                    if (res == null) {
                        ++this.andMisses;
                    }
                    else {
                        ++this.andHits;
                    }
                }
                if (res == null) {
                    ++this.count;
                    if (this.count > this.limit) {
                        throw new BuiltTooManyException();
                    }
                    res = new AndFormula<T>(args);
                    this.ANDS.put(argsSet, res);
                }
                return res;
            }
        }
    }

    @Override
    public Formula<T> buildOr(List<Formula<T>> fmlae) {
        switch (fmlae.size()) {
        case 0:
            return this.ZERO;
        case 1:
            return fmlae.get(0);
        default:
            // only necessary to check the elements of fmlae since
            // OrFormula.args.get(k) instanceof OrFormula cannot occur
            Set<Formula<T>> argsSet = new LinkedHashSet<Formula<T>>((fmlae.size()*11)/10);
            for (Formula<T> formula : fmlae) {
                if (formula == this.ZERO) {
                    continue;
                }
                if (formula == this.ONE) {
                    return formula;
                }
                if (formula instanceof OrFormula) {
                    OrFormula<T> orFormula = (OrFormula<T>) formula;
                    argsSet.addAll(orFormula.args);
                } else {
                    argsSet.add(formula);
                }
            }
            List<Formula<T>> args = new ArrayList<Formula<T>>(argsSet);
            switch (args.size()) {
            case 0:
                return this.ZERO;
            case 1:
                return args.get(0);
            default:
                Formula<T> res = this.ORS.get(argsSet);
                if (Globals.DEBUG_FUHS) {
                    if (res == null) {
                        ++this.orMisses;
                    }
                    else {
                        ++this.orHits;
                    }
                }
                if (res == null) {
                    ++this.count;
                    if (this.count > this.limit) {
                        throw new BuiltTooManyException();
                    }
                    res = new OrFormula<T>(args);
                    this.ORS.put(argsSet, res);
                }
                return res;
            }
        }
    }
}
