package aprove.verification.oldframework.PropositionalLogic.Formulae;

import java.util.*;

import aprove.*;
import aprove.verification.oldframework.PropositionalLogic.*;

/**
 * Builds formulae. Caches each formula ever generated by this such
 * that we will automatically achieve formula sharing (circuit
 * sharing actually, since shared formulae == circuits)
 *
 * @author Patrick Kabasci (based on FullSharingFlatteningFactory)
 * @version $Id$
 */
public class FullSharingExpandingFactory<T> extends AbstractCircuitFactory<T> {

    @Override
    public <U> FormulaFactory<U> toTheory() {
        return new FullSharingExpandingFactory<U>();
    }

    // Flattening
    /*
    public Formula<T> buildAnd(List<? extends Formula> fmlae) {
        switch (fmlae.size()) {
        case 0:
            return this.ONE;
        case 1:
            return fmlae.get(0);
        default:
            // only necessary to check the elements of fmlae since
            // AndFormula.args.get(k) instanceof AndFormula cannot occur
            Set<Formula> argsSet = new LinkedHashSet<Formula>((fmlae.size()*11)/10);
            for (Formula formula : fmlae) {
                if (formula == this.ZERO) {
                    return formula;
                }
                if (formula == this.ONE) {
                    continue;
                }
                if (formula instanceof AndFormula) {
                    AndFormula andFormula = (AndFormula) formula;
                    argsSet.addAll(andFormula.args);
                } else {
                    argsSet.add(formula);
                }
            }
            List<Formula> args = new ArrayList<Formula>(argsSet);
            switch (args.size()) {
            case 0:
                return this.ONE;
            case 1:
                return args.get(0);
            default:
                AndFormula res = this.ANDS.get(argsSet);
                if (Globals.DEBUG_FUHS) {
                    if (res == null) {
                        ++this.andMisses;
                    }
                    else {
                        ++this.andHits;
                    }
                }
                if (res == null) {
                    res = new AndFormula(args);
                    this.ANDS.put(argsSet, res);
                }
                return res;
            }
        }
    }*/

    // Comb
    @Override
    public Formula<T> buildAnd(List<? extends Formula<T>> fmlae) {
        switch (fmlae.size()) {
        case 0:
            return this.ONE;
        case 1:
            return fmlae.get(0);
        default:
            // only necessary to check the elements of fmlae since
            // AndFormula.args.get(k) instanceof AndFormula cannot occur
            Set<Formula<T>> argsSet = new LinkedHashSet<Formula<T>>((fmlae.size()*11)/10);
            for (Formula<T> formula : fmlae) {
                if (formula == this.ZERO) {
                    return formula;
                }
                if (formula == this.ONE) {
                    continue;
                }
            }

            List<Formula<T>> args = new ArrayList<Formula<T>>(argsSet);
            switch (args.size()) {
            case 0:
                return this.ONE;
            case 1:
                return args.get(0);
            case 2:
                Formula<T> res = this.ANDS.get(argsSet);
                if (Globals.DEBUG_FUHS) {
                    if (res == null) {
                        ++this.andMisses;
                    }
                    else {
                        ++this.andHits;
                    }
                }
                if (res == null) {
                    res = new AndFormula<T>(args);
                    this.ANDS.put(argsSet, res);
                }
                return res;

            default:
                // We need to expand the formula (if not yet present).
                Formula<T> nAryRes = this.ANDS.get(argsSet);
                if (Globals.DEBUG_FUHS) {
                    if (nAryRes == null) {
                        ++this.andMisses;
                    }
                    else {
                        ++this.andHits;
                    }
                }
                if (nAryRes == null) {
                    List<Formula<T>> yRes = new ArrayList<Formula<T>>(argsSet.size() / 2 + 1);
                    for(int i=1; i < args.size(); i++) {
                        yRes.add (args.get(i));
                    }
                    List<Formula<T>> andArgs = new ArrayList<Formula<T>>(2);
                    andArgs.add (args.get(0));
                    andArgs.add (this.buildAnd(yRes));
                    res = new AndFormula<T>(andArgs);
                    this.ANDS.put(argsSet, res);
                }
                return nAryRes;
            }
        }
    }

    // Balanced Tree
    /*public Formula buildAnd(List<? extends Formula> fmlae) {
        switch (fmlae.size()) {
        case 0:
            return this.ONE;
        case 1:
            return fmlae.get(0);
        default:
            // only necessary to check the elements of fmlae since
            // AndFormula.args.get(k) instanceof AndFormula cannot occur
            Set<Formula> argsSet = new LinkedHashSet<Formula>((fmlae.size()*11)/10);
            for (Formula formula : fmlae) {
                if (formula == this.ZERO) {
                    return formula;
                }
                if (formula == this.ONE) {
                    continue;
                }
            }

            List<Formula> args = new ArrayList<Formula>(argsSet);
            switch (args.size()) {
            case 0:
                return this.ONE;
            case 1:
                return args.get(0);
            case 2:
                AndFormula res = this.ANDS.get(argsSet);
                if (Globals.DEBUG_FUHS) {
                    if (res == null) {
                        ++this.andMisses;
                    }
                    else {
                        ++this.andHits;
                    }
                }
                if (res == null) {
                    res = new AndFormula(args);
                    this.ANDS.put(argsSet, res);
                }
                return res;

            default:
                // We need to expand the formula (if not yet present).
                AndFormula nAryRes = this.ANDS.get(argsSet);
                if (Globals.DEBUG_FUHS) {
                    if (res == null) {
                        ++this.andMisses;
                    }
                    else {
                        ++this.andHits;
                    }
                }
                if (nAryRes == null) {
                    List<Formula> xRes = new ArrayList<Formula>(argsSet.size() / 2 + 1);
                    List<Formula> yRes = new ArrayList<Formula>(argsSet.size() / 2 + 1);
                    for (int i = 0; i < ((args.size() / 2) + args.size() % 2) ; i++ ) {
                        xRes.add( args.get(i));
                    }
                    for(int i=((args.size() / 2) + args.size() % 2); i < args.size(); i++) {
                        yRes.add (args.get(i));
                    }
                    List<Formula> andArgs = new ArrayList<Formula>(2);
                    andArgs.add (this.buildAnd(xRes));
                    andArgs.add (this.buildAnd(yRes));
                    res = new AndFormula(andArgs);
                    this.ANDS.put(argsSet, res);
                }
                return nAryRes;
            }
        }
    }*/

    /*
    // Balanced tree
    public Formula buildOr(List<Formula> fmlae) {
        switch (fmlae.size()) {
        case 0:
            return this.ONE;
        case 1:
            return fmlae.get(0);
        default:
            // only necessary to check the elements of fmlae since
            // OrFormula.args.get(k) instanceof OrFormula cannot occur
            Set<Formula> argsSet = new LinkedHashSet<Formula>((fmlae.size()*11)/10);
            for (Formula formula : fmlae) {
                if (formula == this.ZERO) {
                    return formula;
                }
                if (formula == this.ONE) {
                    continue;
                }
            }

            List<Formula> args = new ArrayList<Formula>(argsSet);
            switch (args.size()) {
            case 0:
                return this.ONE;
            case 1:
                return args.get(0);
            case 2:
                OrFormula res = this.ORS.get(argsSet);
                if (Globals.DEBUG_FUHS) {
                    if (res == null) {
                        ++this.orMisses;
                    }
                    else {
                        ++this.orHits;
                    }
                }
                if (res == null) {
                    res = new OrFormula(args);
                    this.ORS.put(argsSet, res);
                }
                return res;

            default:
                // We need to expOr the formula (if not yet present).
                OrFormula nAryRes = this.ORS.get(argsSet);
                if (Globals.DEBUG_FUHS) {
                    if (res == null) {
                        ++this.orMisses;
                    }
                    else {
                        ++this.orHits;
                    }
                }
                if (nAryRes == null) {
                    List<Formula> xRes = new ArrayList<Formula>(argsSet.size() / 2 + 1);
                    List<Formula> yRes = new ArrayList<Formula>(argsSet.size() / 2 + 1);
                    for (int i = 0; i < ((args.size() / 2) + args.size() % 2) ; i++ ) {
                        xRes.add( args.get(i));
                    }
                    for(int i=((args.size() / 2) + args.size() % 2); i < args.size(); i++) {
                        yRes.add (args.get(i));
                    }
                    List<Formula> OrArgs = new ArrayList<Formula>(2);
                    OrArgs.add (this.buildOr(xRes));
                    OrArgs.add (this.buildOr(yRes));
                    res = new OrFormula(OrArgs);
                    this.ORS.put(argsSet, res);
                }
                return nAryRes;
            }
        }
    }*/

    // Comb
    @Override
    public Formula<T> buildOr(List<Formula<T>> fmlae) {
        switch (fmlae.size()) {
        case 0:
            return this.ONE;
        case 1:
            return fmlae.get(0);
        default:
            // only necessary to check the elements of fmlae since
            // OrFormula.args.get(k) instanceof OrFormula cannot occur
            Set<Formula<T>> argsSet = new LinkedHashSet<Formula<T>>((fmlae.size()*11)/10);
            for (Formula<T> formula : fmlae) {
                if (formula == this.ZERO) {
                    return formula;
                }
                if (formula == this.ONE) {
                    continue;
                }
            }

            List<Formula<T>> args = new ArrayList<Formula<T>>(argsSet);
            switch (args.size()) {
            case 0:
                return this.ONE;
            case 1:
                return args.get(0);
            case 2:
                Formula<T> res = this.ORS.get(argsSet);
                if (Globals.DEBUG_FUHS) {
                    if (res == null) {
                        ++this.orMisses;
                    }
                    else {
                        ++this.orHits;
                    }
                }
                if (res == null) {
                    res = new OrFormula<T>(args);
                    this.ORS.put(argsSet, res);
                }
                return res;

            default:
                // We need to expand the formula (if not yet present).
                Formula<T> nAryRes = this.ORS.get(argsSet);
                if (Globals.DEBUG_FUHS) {
                    if (nAryRes == null) {
                        ++this.orMisses;
                    }
                    else {
                        ++this.orHits;
                    }
                }
                if (nAryRes == null) {
                    List<Formula<T>> yRes = new ArrayList<Formula<T>>(argsSet.size() / 2 + 1);
                    for(int i=1; i < args.size(); i++) {
                        yRes.add (args.get(i));
                    }
                    List<Formula<T>> OrArgs = new ArrayList<Formula<T>>(2);
                    OrArgs.add (args.get(0));
                    OrArgs.add (this.buildOr(yRes));
                    res = new OrFormula<T>(OrArgs);
                    this.ORS.put(argsSet, res);
                }
                return nAryRes;
            }
        }
    }
}
