package aprove.verification.oldframework.PropositionalLogic.Formulae;

import java.util.*;

import aprove.*;
import aprove.verification.oldframework.PropositionalLogic.*;

/**
 * Builds formulae. Caches each formula ever generated by this such
 * that we will automatically achieve formula sharing (circuit
 * sharing actually, since shared formulae == circuits).
 *
 * Only optimizes away ZERO, ONE and multiple occurrences of
 * arguments, but does not flatten nested occurrences of any kind
 * of boolean connective except "not".
 *
 * @author Peter Schneider-Kamp, Carsten Fuhs
 * @version $Id$
 */
public class FullSharingFactory<T> extends AbstractCircuitFactory<T> {

    @Override
    public <U> FormulaFactory<U> toTheory() {
        return new FullSharingFactory<U>();
    }

    @Override
    public Formula<T> buildAnd(List<? extends Formula<T>> fmlae) {
        switch (fmlae.size()) {
        case 0:
            return this.ONE;
        case 1:
            return fmlae.get(0);
        default:
            Set<Formula<T>> argsSet = new LinkedHashSet<Formula<T>>((fmlae.size()*11)/10);
            for (Formula<T> formula : fmlae) {
                if (formula == this.ZERO) {
                    return formula;
                }
                if (formula == this.ONE) {
                    continue;
                }
                argsSet.add(formula);
            }
            List<Formula<T>> args = new ArrayList<Formula<T>>(argsSet);
            switch (args.size()) {
            case 0:
                return this.ONE;
            case 1:
                return args.get(0);
            default:
                Formula<T> res = this.ANDS.get(argsSet);
                if (Globals.DEBUG_FUHS) {
                    if (res == null) {
                        ++this.andMisses;
                    }
                    else {
                        ++this.andHits;
                    }
                }
                if (res == null) {
                    res = new AndFormula<T>(args);
                    this.ANDS.put(argsSet, res);
                }
                return res;
            }
        }
    }

    @Override
    public Formula<T> buildOr(List<Formula<T>> fmlae) {
        switch (fmlae.size()) {
        case 0:
            return this.ZERO;
        case 1:
            return fmlae.get(0);
        default:
            Set<Formula<T>> argsSet = new LinkedHashSet<Formula<T>>((fmlae.size()*11)/10);
            for (Formula<T> formula : fmlae) {
                if (formula == this.ZERO) {
                    continue;
                }
                if (formula == this.ONE) {
                    return formula;
                }
                argsSet.add(formula);
            }
            List<Formula<T>> args = new ArrayList<Formula<T>>(argsSet);
            switch (args.size()) {
            case 0:
                return this.ZERO;
            case 1:
                return args.get(0);
            default:
                Formula<T> res = this.ORS.get(argsSet);
                if (Globals.DEBUG_FUHS) {
                    if (res == null) {
                        ++this.orMisses;
                    }
                    else {
                        ++this.orHits;
                    }
                }
                if (res == null) {
                    res = new OrFormula<T>(args);
                    this.ORS.put(argsSet, res);
                }
                return res;
            }
        }
    }
}
