package aprove.verification.oldframework.PropositionalLogic.Formulae;

import java.util.*;

import aprove.*;
import aprove.verification.oldframework.PropositionalLogic.*;
import aprove.verification.oldframework.Utility.GenericStructures.*;

/**
 * Builds formulae. Caches each formula ever generated by this such
 * that we will automatically achieve formula sharing (circuit
 * sharing actually, since shared formulae == circuits).
 *
 * Note: Most of the lists you pass to the constructor will be incorporated
 * directly into the constructed formulae, so any changes you make to the
 * lists afterwards will be reflected in the formulae.
 *
 * Note: Does not perform any Boolean optimizations!
 * Sharing is performed based on argument /lists/.
 *
 * @author Peter Schneider-Kamp, Carsten Fuhs
 * @version $Id$
 */
public class ListSharingFactory<T> extends AbstractFormulaFactory<T> {

    protected final Map<Formula<T>, Formula<T>> NOTS = new HashMap<Formula<T>, Formula<T>>();
    protected final Map<List<? extends Formula<T>>, Formula<T>> ANDS = new HashMap<List<? extends Formula<T>>, Formula<T>>();
    protected final Map<List<Formula<T>>, Formula<T>> ORS = new HashMap<List<Formula<T>>, Formula<T>>();
    protected final Map<List<Formula<T>>, Formula<T>> XORS = new HashMap<List<Formula<T>>, Formula<T>>();
    protected final Map<Pair<Formula<T>, Formula<T>>, Formula<T>> IFFS = new HashMap<Pair<Formula<T>, Formula<T>>, Formula<T>>();
    protected final Map<Triple<Formula<T>, Formula<T>, Formula<T>>, Formula<T>> ITES = new HashMap<Triple<Formula<T>, Formula<T>, Formula<T>>, Formula<T>>();
    protected final Map<Pair<List<Formula<T>>, Integer>, Formula<T>> ATLEASTS = new HashMap<Pair<List<Formula<T>>, Integer>, Formula<T>>();
    protected final Map<Pair<List<Formula<T>>, Integer>, Formula<T>> ATMOSTS = new HashMap<Pair<List<Formula<T>>, Integer>, Formula<T>>();
    protected final Map<Pair<List<Formula<T>>, Integer>, Formula<T>> COUNTS = new HashMap<Pair<List<Formula<T>>, Integer>, Formula<T>>();
    protected final Map<T, TheoryAtom<T>> THEORY_ATOMS = new HashMap<T, TheoryAtom<T>>();

    // evaluate which caches are actually used productively
    public int notHits = 0;
    public int notMisses = 0;
    public int andHits = 0;
    public int andMisses = 0;
    public int orHits = 0;
    public int orMisses = 0;
    public int xorHits = 0;
    public int xorMisses = 0;
    public int iffHits = 0;
    public int iffMisses = 0;
    public int theoryHits = 0;
    public int theoryMisses = 0;

    public static <U> ListSharingFactory<U> create() {
        return new ListSharingFactory<U>();
    }

    @Override
    public <U> FormulaFactory<U> toTheory() {
        return new ListSharingFactory<U>();
    }

    @Override
    public TheoryAtom<T> buildTheoryAtom(T t) {
        TheoryAtom<T> res = this.THEORY_ATOMS.get(t);
        if (Globals.DEBUG_FUHS) {
            if (res == null) {
                ++this.theoryMisses;
            }
            else {
                ++this.theoryHits;
            }
        }
        if (res == null) {
            res = new TheoryAtom<T>(t);
            this.THEORY_ATOMS.put(t, res);
        }
        return res;
    }

    @Override
    public Formula<T> buildNot(Formula<T> fml) {
        Formula<T> res = this.NOTS.get(fml);
        if (Globals.DEBUG_FUHS) {
            if (res == null) {
                ++this.notMisses;
            }
            else {
                ++this.notHits;
            }
        }
        if (res == null) {
            res = new NotFormula<T>(fml);
            this.NOTS.put(fml, res);
        }
        return res;
   }

    @Override
    public Formula<T> buildAnd(List<? extends Formula<T>> fmlae) {
        switch (fmlae.size()) {
        case 0:
            return this.ONE;
        case 1:
            return fmlae.get(0);
        default:
            Formula<T> res = this.ANDS.get(fmlae);
            if (Globals.DEBUG_FUHS) {
                if (res == null) {
                    ++this.andMisses;
                }
                else {
                    ++this.andHits;
                }
            }
            if (res == null) {
                res = new AndFormula<T>(fmlae);
                this.ANDS.put(fmlae, res);
            }
            return res;
        }
    }

    @Override
    public Formula<T> buildOr(List<Formula<T>> fmlae) {
        switch (fmlae.size()) {
        case 0:
            return this.ZERO;
        case 1:
            return fmlae.get(0);
        default:
            Formula<T> res = this.ORS.get(fmlae);
            if (Globals.DEBUG_FUHS) {
                if (res == null) {
                    ++this.orMisses;
                }
                else {
                    ++this.orHits;
                }
            }
            if (res == null) {
                res = new OrFormula<T>(fmlae);
                this.ORS.put(fmlae, res);
            }
            return res;
        }
    }

    @Override
    public Formula<T> buildXor(List<Formula<T>> fmlae) {
        switch (fmlae.size()) {
        case 0:
            return this.ZERO;
        case 1:
            return fmlae.get(0);
        default:
            Formula<T> res = this.XORS.get(fmlae);
            if (Globals.DEBUG_FUHS) {
                if (res == null) {
                    ++this.xorMisses;
                }
                else {
                    ++this.xorHits;
                }
            }
            if (res == null) {
                res = new XorFormula<T>(fmlae);
                this.XORS.put(fmlae, res);
            }
            return res;
        }
    }

    @Override
    public Formula<T> buildIff(Formula<T> left, Formula<T> right) {
        Pair<Formula<T>, Formula<T>> lr = new Pair<Formula<T>, Formula<T>>(left, right);
        Formula<T> res = this.IFFS.get(lr);

        if (Globals.DEBUG_FUHS) {
            if (res == null) {
                ++this.iffMisses;
            }
            else {
                ++this.iffHits;
            }
        }

        if (res == null) {
            res = new IffFormula<T>(left, right);
            this.IFFS.put(lr, res);
        }
        return res;
    }

    @Override
    public Formula<T> buildIte(Formula<T> condition, Formula<T> thenFormula,
            Formula<T> elseFormula) {
        Triple<Formula<T>, Formula<T>, Formula<T>> lr = new Triple<Formula<T>, Formula<T>, Formula<T>>(condition,
                thenFormula, elseFormula);
        Formula<T> res = this.ITES.get(lr);

        if (res == null) {
            res = new IteFormula<T>(condition, thenFormula, elseFormula);
            this.ITES.put(lr, res);
        }
        return res;
    }

    @Override
    public Formula<T> buildAtLeast(List<Formula<T>> fmlae, int cardinality) {
        if (Globals.useAssertions) {
            assert cardinality >= 0;
        }
        final int fmlaeSize = fmlae.size();

        switch (fmlaeSize) {
        case 0:
            return cardinality == 0 ? this.ONE : this.ZERO;
        case 1:
            return cardinality == 1 ? fmlae.get(0) : this.ZERO;
        default:
            Pair<List<Formula<T>>, Integer> argsListWithCard =
                    new Pair<List<Formula<T>>, Integer>(fmlae,
                            cardinality);
            Formula<T> res = this.ATLEASTS.get(argsListWithCard);
            if (res == null) {
                res = new AtLeastFormula<T>(fmlae, cardinality);
                this.ATLEASTS.put(argsListWithCard, res);
            }
            return res;
        }
    }
}
