package aprove.verification.theoremprover.TheoremProverProcedures;

/**
 * The InteractiveLemmaApplicationProcessor shows the user
 * a list of all possible lemma applications with their result
 * to let the user decide with which to go on for proving.
 *
 * @author dickmeis
 * @version $Id$
 */

import java.util.*;

import javax.swing.*;

import aprove.prooftree.Obligations.*;
import aprove.strategies.Abortions.*;
import aprove.strategies.Annotations.*;
import aprove.strategies.ExecutableStrategies.*;
import aprove.verification.dpframework.*;
import aprove.verification.oldframework.LemmaApplication.*;
import aprove.verification.oldframework.LemmaDatabase.*;
import aprove.verification.oldframework.Logic.*;
import aprove.verification.oldframework.Logic.Formulas.*;
import aprove.verification.oldframework.TheoremProverProblem.*;
import aprove.verification.theoremprover.TheoremProverProofs.*;


@NoParams
public class InteractiveLemmaApplicationProcessor extends TheoremProverProcessor {

    /**
     * constructor used by param manager via reflection
     */
    public InteractiveLemmaApplicationProcessor() {
        super(false);
    }

    @Override
    protected Result process(TheoremProverObligation obligationInput, BasicObligationNode obligationNode, Abortion aborter,
                RuntimeInformation rti) throws AbortionException {

        // get formula
        Formula formula = obligationInput.getFormula();

        Set<Formula> lemmas;

        // get lemmas
        lemmas = LemmaDatabaseFactory.getLemmmaDatabase().retrieveAllFormulas();

        ArrayList<LemmaApplicationResult> results = LemmaApplicationVisitorAll.apply(formula, lemmas);

        if(results.isEmpty()) {
            // no lemma is applicable
            JDialog jd = new JDialog();
            jd.setTitle("Not applicable");
            jd.setContentPane(new JLabel("No lemma is applicable."));
            jd.setSize(300, 30);
            jd.setModal(true);
            jd.setVisible(true);

            return ResultFactory.notApplicable();
        }

        for (int i = 0; i < results.size(); i++) {
            LemmaApplicationResult r1 = results.get(i);
            for (int j = i; j < results.size(); j++) {
                LemmaApplicationResult r2 = results.get(j);
                if (!r1.equals(r2) &&
                        r1.getResult().equals(r2.getResult()) &&
                        r1.getLemma().equals(r2.getLemma()))
                    // the same result is generated by using the same lemma
                    // (but at different positions)
                    // so we can ignore one
                    {
                    r2.setUnusful();
                }
            }
        }


        Set<Formula> ancestorFormulas = obligationInput.getAncestorFormulas();

        for (Iterator iter = results.iterator(); iter.hasNext();) {
            LemmaApplicationResult r = (LemmaApplicationResult) iter.next();

            if (ancestorFormulas.contains(r.getResult())){
                r.setUnusful();
            }
        }

        Collections.sort(results);
        Collections.reverse(results);

        ArrayList<TheoremProverObligation> newObligations = new ArrayList<TheoremProverObligation>();
        ArrayList<LemmaApplicationResult> usedresult = new ArrayList<LemmaApplicationResult>();

        for (LemmaApplicationResult t : results) {
            if (t.isSelected()){
                TheoremProverObligation newObligation = new TheoremProverObligation(t.getResult(),obligationInput);

                ArrayList<Formula> usedLemmas = new ArrayList<Formula>();
                usedLemmas.add(t.getLemma());
                newObligation.addUsedLemmas(usedLemmas);

                newObligations.add(newObligation);
                usedresult.add(t);
            }
        }

        LemmaApplicationProof lap = new LemmaApplicationProof(usedresult);


        if (newObligations.size() == 0){
            return ResultFactory.notApplicable();
        }
        else if (newObligations.size() == 1){
            return ResultFactory.proved(newObligations.get(0),YNMImplication.EQUIVALENT, lap);
        }
        else{
            return ResultFactory.provedOr(newObligations,YNMImplication.EQUIVALENT, lap);
        }

    }

}
