#ALL is handled internally
CLS = Clousot program (*.cls):cls
TRS = Term Rewrite Systems (*.trs):trs
TES = Term Rewrite Systems (*.tes):tes
TTT = Term Rewrite Systems (*.ttt):ttt
XTRS = Term Rewrite Systems (*.xtrs):xtrs
SRS = String Rewrite Systems (*.srs):srs
SES = String Rewrite Systems (*.ses):ses
XSRS = String Rewrite Systems (*.xsrs):xsrs
PROLOG = Prolog Programs (*.pl):pl
FP = Functional Programs (*.fp):fp
IDP = Integer DP Problem (*.idp):idp
IPAD = Imperative Programs (*.ipad):ipad
ITRS = Integer TRS Problem (*.itrs):itrs
JBC = Java Byte Code Programs (*.class *.jar):class jar
HASKELL = Haskell Programs (*.hs):hs
HTML = HyperText Markup Language (*.html):html
TEX = LaTeX Sources (*.tex):tex
TXT = Plain text (*.txt):txt
ALLFOL = First Order Formulas (*.fol *.xfol):fol xfol
#FOL = First Order Formulas (*.fol):fol
XFOL First Order Formulas (*.xfol):xfol
TRM = Terms (*.trm):trm
XML = XML Term File (*.xml):xml
XTC = XML Termination C? (*.xtc):xtc xml
APL = AProVE Program List (*.apl):apl
OBL = AProVE Obligations (*.obl):obl
DOT = Graphviz (*.dot):dot
APROVE = AProVE Programs (*.cls, *.trs, *.tes, *.ttt, *.xtrs, *srs, *.ses, *.xsrs, *.pl, *.fp, *.idp, *.ipad, *.itrs, *.class, *.jar, *.hs, *.qdp, *.qtrs, *.strs, *.patrs, *.xml, *.xtc, *.obl):cls trs tes ttt xtrs srs ses xsrs pl fp idp ipad itrs class jar hs qdp qtrs strs patrs xml xtc obl
BATCH = Batchmode (*.trs, *.tes, *.ttt, *.xtrs, *.srs, *.ses, *.xsrs, *.pl, *.fp, *.idp, *.ipad, *.itrs, *.class, *.jar, *.hs, *.qdp, *.qtrs, *.apl, *.xml, *.xtc, *.obl):trs tes ttt xtrs srs ses xsrs pl fp idp ipad itrs class jar hs qdp qtrs apl xml xtc obl
STRATEGY = Strategies(*.strategy):strategy
LDB = Lemma database(*.ldb):ldb
PROOF = AProVE Proof (*.apr):apr
QDP = QDP Problem (*.qdp):qdp
QTRS = QTRS Problem (*.qtrs):qtrs
STRS = Sorted Term Rewrite Systems (*.strs):strs
PATRS = PA-based TRS (*.patrs):patrs
_APROVEPROOF = PROOF

_OPEN = ALL APL APROVE
_SAVENORM = CLS PATRS HASKELL PROLOG FP IDP IPAD ITRS JBC TTT XTRS SRS SES XSRS TRS TES QDP QTRS
_SAVEAPL = APL
_SAVEGRAPH = DOT
_EXPORTHTML = ALL HTML
_EXPORTTEX = ALL TEX
_EXPORTPLAIN = ALL TXT
_LOG = ALL
_FOL = FOL
_SAVEFOL = XFOL
_LOADFOL = XFOL
_TRM = TRM
_XML = XML
_LOADSTRATEGY = STRATEGY
_SAVESTRATEGY = STRATEGY
_LOADLDB = LDB TXT
_SAVELDB = LDB
