ORDERS = EMB LPO LPOS RPO RPOS PPO ACRPOS POLO MATRO KBO

#------------------------------------------------------------------------------
# EMB
#------------------------------------------------------------------------------
EMB.DisplayName = Homeomorphic Embedding Order
EMB.Factory = aprove.solver.EMBFactory
EMB.breadth = true
EMB.quasi = false
EMB.restriction = 2

#------------------------------------------------------------------------------
# LPO
#------------------------------------------------------------------------------
LPO.DisplayName = Lexicographic Path Order
LPO.Factory = aprove.solver.LPOFactory
LPO.breadth = true
LPO.quasi = false
LPO.restriction = 2

#------------------------------------------------------------------------------
# LPOS
#------------------------------------------------------------------------------
LPOS.DisplayName = Lexicographic Path Order with Status
LPOS.Factory = aprove.solver.LPOSFactory
LPOS.breadth = true
LPOS.quasi = false
LPOS.restriction = 2

#------------------------------------------------------------------------------
# RPO
#------------------------------------------------------------------------------
RPO.DisplayName = Recursive Path Order
RPO.Factory = aprove.solver.RPOFactory
RPO.breadth = true
RPO.quasi = false
RPO.restriction = 2

#------------------------------------------------------------------------------
# RPOS
#------------------------------------------------------------------------------
RPOS.DisplayName = Recursive Path Order with Status
RPOS.Factory = aprove.solver.RPOSFactory
RPOS.breadth = true
RPOS.quasi = false
RPOS.restriction = 2

#------------------------------------------------------------------------------
# PPO
#------------------------------------------------------------------------------
PPO.DisplayName = Parameterizable Path Order
PPO.Factory = aprove.solver.PPOFactory
PPO.breadth = true
PPO.quasi = false
PPO.restriction = 2

#------------------------------------------------------------------------------
# ACRPOS
#------------------------------------------------------------------------------
ACRPOS.DisplayName = AC-Compatible Recursive Path Order with Status
ACRPOS.Factory = aprove.solver.ACRPOSFactory
ACRPOS.quasi = false
ACRPOS.restriction = 2

#------------------------------------------------------------------------------
# POLO
#------------------------------------------------------------------------------
POLO.DisplayName = Polynomial Ordering
POLO.Factory = aprove.solver.POLOFactory

# valid values for POLO.degree are
#   > -1 = SIMPLE
#   >  0 = SIMPLE_MIXED
#   > any value greater than 0
POLO.degree = 1

POLO.range = 1

POLO.maxSimpleDegree = 4

POLO.autostrict = true
POLO.autostrict_jar = true

POLO.restriction = 2

#------------------------------------------------------------------------------
# MATRO
#------------------------------------------------------------------------------
MATRO.Factory = aprove.solver.MATROFactory
MATRO.range = 1
MATRO.restriction = 2
MATRO.size = 2
MATRO.type = COLLAPSINGDPTUPLE
MATRO.degree = aprove.verification.oldframework.Algebra.Matrices.Interpretation.LinearArgumentInterpretor

#------------------------------------------------------------------------------
# LIMITPOLO
#------------------------------------------------------------------------------
LimitPOLO.Factory = aprove.solver.LimitPOLOFactory
LimitPOLO.range = 1


#------------------------------------------------------------------------------
# KBO
#------------------------------------------------------------------------------
KBO.DisplayName = Knuth-Bendix Order
KBO.Factory = aprove.solver.KBOFactory
KBO.breadth = false
KBO.quasi = false
KBO.restriction = 2
