FOLDER="../examples"
SUBDIR="C"
CATEGORY="default"
# No handlers/default.sh; solver will fall back to __default__.sh
TIMEOUT="10"
#IMAGE=<DOCKER_IMAGE>
OUTDIR="example_results/C"
APROVE_JAR="../dist/lib/aprove.jar"
EXTENSION="c"
