FOLDER="../examples"
SUBDIR="ITRS_Innermost"
CATEGORY="ITRS_Innermost"
# No handlers/ITRS_Innermost.py; solver falls back to __default__.py
TIMEOUT="30"
#IMAGE=<DOCKER_IMAGE>
OUTDIR="example_results/ITRS_Innermost"
APROVE_JAR="../dist/lib/aprove.jar"
EXTENSION="itrs"
