FOLDER="../examples"
SUBDIR="Integer_Transition_Systems"
CATEGORY="ITRS_Innermost"
# No handlers/ITRS_Innermost.sh; solver will fall back to __default__.sh
TIMEOUT="10"
#IMAGE=<DOCKER_IMAGE>
OUTDIR="example_results/ITRS_Innermost"
APROVE_JAR="../dist/lib/aprove.jar"
EXTENSION="ari"
