FOLDER="../examples"
SUBDIR="Logic_Programming"
CATEGORY="Logic_Programming"
# No handlers/Logic_Programming.sh; solver will fall back to __default__.sh
TIMEOUT="10"
#IMAGE=<DOCKER_IMAGE>
OUTDIR="example_results/Logic_Programming"
APROVE_JAR="../dist/lib/aprove.jar"
EXTENSION="pl"
