FOLDER="../examples"
SUBDIR="SRS_Standard"
CATEGORY="SRS_Standard"
# No handlers/SRS_Standard.sh; solver will fall back to __default__.sh
TIMEOUT="10"
#IMAGE=<DOCKER_IMAGE>
OUTDIR="example_results/SRS_Standard"
APROVE_JAR="../dist/lib/aprove.jar"
EXTENSION="ari"
