package aprove.verification.dpframework.TRSProblem.Processors;

import java.util.*;
import java.util.Map.Entry;

import aprove.*;
import aprove.prooftree.Export.Utility.*;
import aprove.runtime.*;
import aprove.strategies.Abortions.*;
import aprove.strategies.Annotations.*;
import aprove.strategies.ExecutableStrategies.*;
import aprove.verification.dpframework.*;
import aprove.verification.dpframework.BasicStructures.*;
import aprove.verification.dpframework.TRSProblem.*;
import aprove.verification.oldframework.BasicStructures.*;
import aprove.verification.oldframework.Logic.*;
import aprove.verification.oldframework.Utility.*;
import aprove.verification.oldframework.Utility.GenericStructures.*;

/**
 * Implements inverse of the complete Giesl-Middeldorp transformation to convert
 * TRS problems to CSR problems.
 *
 * See "Transformation Techniques for Context-Sensitive Rewrite Systems",
 * Journal of Functional Programming, 14(4): 379-427, 2004.
 *
 * @author noschinski
 * @version $Id$
 */
@NoParams
public class QTRSToCSRProcessor extends QTRSProcessor {

    @Override
    public boolean isQTRSApplicable(final QTRSProblem qtrs) {
        return (qtrs.getQ().isEmpty() || qtrs.isExactlyInnermost()) && !Options.certifier.isCeta();
    }

    @Override
    protected Result processQTRS(final QTRSProblem qtrs, final Abortion aborter, final RuntimeInformation rti)
            throws AbortionException {
        if (!this.hasConstant(qtrs)) {
            return ResultFactory.notApplicable("This QTRS does not contain a " +
                    "constant and is therefore not the image of an application " +
                    "of the complete Giesl-Middeldorp transformation");
        }
        final Map<FunctionSymbol, Set<Rule>> splitRules =
            this.splitRulesByRoot(qtrs.getR());
        final GuessingState gState = this.recognizeSpecialSymbols(splitRules, aborter);
        final CSRProblem csr = this.makeCsr(qtrs, splitRules, gState);

        if (csr == null) {
            return ResultFactory.notApplicable("This QTRS is not the image of an " +
                    "application of the complete Giesl-Middeldorp transformation");
        } else {
            final boolean complete = qtrs.getQ().isEmpty() && gState.checkComplete(qtrs.getRSignature());
            final Implication impl = complete ?
                    YNMImplication.EQUIVALENT : YNMImplication.SOUND;
            final QTRSProof proof = new QTRSToCSRProof(qtrs, csr, gState, complete);

            if (Globals.useAssertions) {
                assert this.checkCSRcorrectness(qtrs, csr, gState, complete);
            }

            return ResultFactory.proved(csr, impl, proof);
        }
    }

    /**
     * The complete Giesl-Middeldorp transformation assumes the existence of
     * at least one constant symbol in the signature. As none of the newly
     * introduced function symbols is a constant, the TRS contains a constant
     * if and only iff the signature of the CSR contained a constant.
     */
    private boolean hasConstant(final QTRSProblem qtrs) {
        for (final FunctionSymbol fs : qtrs.getSignature()) {
            if (fs.getArity() == 0) {
                return true;
            }
        }
        return false;
    }

    /*
     * Check that our computation was correct. For a sound
     * transformation, the qtrs rules must be a subset of the rules
     * generated by applying the complete GieslMiddeldorp transformation
     * to the result of the inverse complete GM transformation. For a sound and complete
     * transformation, both sets have to be equal.
     */
    private boolean checkCSRcorrectness(final QTRSProblem qtrs, final CSRProblem csr, final GuessingState gState, final boolean complete) {
        final FunctionSymbol proper = gState.getProper();
        final FunctionSymbol ok = gState.getOk();

        /* transform the generated CSR back into a TSR problem */
        final Set<Rule> transRules =
            CSRToQTRSProcessor.CompleteGieslMiddeldorpTransformation.transform(
                    csr.getR(), csr.getReplacementMap(), csr.getInnermost(),
                    gState.getMark().getName(),
                    gState.getProper().getName(),
                    gState.getOk().getName(),
                    gState.getActive().getName(),
                    gState.getTop().getName());

        /*
         * The original system may contain "proper" rules for function symbols
         * not occurring in any rule (for example, compare
         * TPDB07/TRS/CSR/Ex1_2_AEL03.trs and TPDB07/TRS/TRCSR/Ex1_2_AEL03_C.trs -
         * the latter contains a rule "proper(nil) -> ok(nil)", but "nil" occurs
         * only in the replacement map and not in any of the rules). Those
         * proper rules are valid, but do not occur in the back-transformed
         * ruleset.
         */
        final Set<FunctionSymbol> unused = new LinkedHashSet<FunctionSymbol>(qtrs.getSignature());
        final Set<FunctionSymbol> csrSignature = csr.getSignature();

        unused.removeAll(gState.getSpecials());
        unused.removeAll(csrSignature);

        for (final FunctionSymbol sym : unused) {
            if (sym.getArity() == 0) {
                final TRSTerm t = TRSTerm.createFunctionApplication(sym);
                final TRSFunctionApplication lhs = TRSTerm.createFunctionApplication(
                        proper, t);
                final TRSTerm rhs = TRSTerm.createFunctionApplication(
                        ok, t);
                transRules.add(Rule.create(lhs, rhs));
            } else {
                final int arity = sym.getArity();
                final TRSTerm vars[] = new TRSTerm[arity];
                for (int i=0; i < arity; i++) {
                    vars[i] = TRSTerm.createVariable("x" + i);
                }
                final TRSTerm properVars[] = new TRSTerm[arity];
                for (int i=0; i < arity; i++) {
                    properVars[i] = TRSTerm.createFunctionApplication(proper, vars[i]);
                }
                final TRSFunctionApplication lhs = TRSTerm.createFunctionApplication(
                        proper, TRSTerm.createFunctionApplication(sym, vars));
                final TRSTerm rhs = TRSTerm.createFunctionApplication(sym, properVars);
                transRules.add(Rule.create(lhs, rhs));
            }
        }

        /* Normalize rules for comparison */
        final Set<Rule> transRulesN = new HashSet<Rule>(transRules.size());
        for (final Rule r : transRules) {
            transRulesN.add(r.getStandardRepresentation());
        }

        final Set<Rule> qtrsRulesN = new HashSet<Rule>(qtrs.getR().size());
        for (final Rule r : qtrs.getR()) {
            qtrsRulesN.add(r.getStandardRepresentation());
        }

        // TODO: Is returning an ERROR-result with a log message better
        // than assert()?
        if (complete) {
            return transRulesN.equals(qtrsRulesN);
        } else {
            return transRulesN.containsAll(qtrsRulesN);
        }
    }

    /**
     * Converts a QTRS to an CSR.
     *
     * @param splitRules
     *            Rules of the QTRS, split by the root symbol of their lhs.
     * @param gState
     *            Guesses for the five special symbols. Behaviour is undefined
     *            if the guesses are not valid!
     */
    private CSRProblem makeCsr(final QTRSProblem qtrs,
            final Map<FunctionSymbol, Set<Rule>> splitRules,
            final GuessingState gState) {
        if (gState == null) {
            return null;
        }

        final FunctionSymbol active = gState.getActive();
        final FunctionSymbol mark = gState.getMark();

        final Set<Rule> R = new LinkedHashSet<Rule>();
        final Set<Rule> activeRules = splitRules.get(active);

        final Set<FunctionSymbol> signature = qtrs.getRSignature();

        final Map<FunctionSymbol, Set<Integer>> replacementMap =
            new HashMap<FunctionSymbol, Set<Integer>>(signature.size());

        for (final FunctionSymbol fs : signature) {
            replacementMap.put(fs, new LinkedHashSet<Integer>());
        }

        for (final Rule r : activeRules) {
            /* extract replacementMap entries from active -> active rules */
            if (!this.hasRootSym(r.getRight(), mark)) {
                final TRSFunctionApplication fa = (TRSFunctionApplication)r.getRight();
                final Set<Integer> replacementEntry =
                    replacementMap.get(fa.getRootSymbol());
                final int size = fa.getArguments().size();
                for (int i=0; i < size; i++) {
                    if (!fa.getArgument(i).isVariable()) {
                        replacementEntry.add(i);
                        break;
                    }
                }
            } else {
                /* so we have an active -> mark rule. strip active, mark.
                 * we know that the rhs is a FunctionApplication. */
                final TRSFunctionApplication lhs = r.getLeft();
                final TRSFunctionApplication rhs = (TRSFunctionApplication)r.getRight();
                R.add(Rule.create((TRSFunctionApplication)lhs.getArgument(0),
                        rhs.getArgument(0)));
            }
        }

        /* extract replacementMap entries from f(x1, ..., mark(xi), ..., xn) -> mark(...) rules */
        for (final Map.Entry<FunctionSymbol,Set<Rule>> entry : splitRules.entrySet()) {
            final FunctionSymbol leftRoot = entry.getKey();
            /* ignore rules starting with a special symbol */
            if (gState.getSpecials().contains(leftRoot)) {
                continue;
            }

            final Set<Integer> newReplacementEntry = new LinkedHashSet<Integer>();
            for (final Rule r : entry.getValue()) {
                if (!this.hasRootSym(r.getRight(), mark)) {
                    continue;
                }

                final TRSFunctionApplication fa = r.getLeft();
                assert(fa.getRootSymbol().equals(leftRoot));
                final int size = fa.getArguments().size();
                for (int i=0; i < size; i++) {
                    if (!fa.getArgument(i).isVariable()) {
                        newReplacementEntry.add(i);
                        break;
                    }
                }
            }

            /*
             * if replacing positions described by active and mark rules differ,
             * our transformation is not complete, just sound.
             */
            final Set<Integer> replacementEntry =
                replacementMap.get(leftRoot);
            if (!replacementEntry.equals(newReplacementEntry)) {
                gState.setNotComplete();
                replacementEntry.addAll(newReplacementEntry);
            }


        }

        return CSRProblem.create(R, replacementMap, false);
    }

    /**
     * Identifies the special symbols (active, mark, proper, ok, top) used in
     * the complete GM transformation.
     *
     * @param splitRules
     *            Rules of the QTRS, split by the root symbol of their lhs.
     */
    private GuessingState recognizeSpecialSymbols(
            final Map<FunctionSymbol, Set<Rule>> splitRules, final Abortion aborter) throws AbortionException {

        final Map<FunctionSymbol, List<Pair<FunctionSymbol, FunctionSymbol>>> topCandidatesMap =
            this.getTopCandidates(splitRules);
        if (topCandidatesMap.isEmpty()) {
            return null;
        }

        aborter.checkAbortion();

        for(final Map.Entry<FunctionSymbol, List<Pair<FunctionSymbol, FunctionSymbol>>> entry
                : topCandidatesMap.entrySet()) {
            final GuessingState gState = new GuessingState(entry.getKey(), entry.getValue());

            if (this.checkOtherSymbols(splitRules, gState)) {
                return gState;
            }

            aborter.checkAbortion();

            gState.next();
            if (this.checkOtherSymbols(splitRules, gState)) {
                return gState;
            }

            aborter.checkAbortion();

        }

        return null;


    }

    /**
     * For a given top symbol, check both possibilities for {(mark, proper),
     * (ok, active)} for validity.
     */
    private boolean checkOtherSymbols(
            final Map<FunctionSymbol, Set<Rule>> splitRules,
            final GuessingState gState) {

        for (final Rule r : splitRules.get(gState.getActive())) {
            if (!this.isActiveRule(r, gState)) {
                return false;
            }
        }

        for (final Rule r : splitRules.get(gState.getProper())) {
            if (!this.isProperRule(r, gState)) {
                return false;
            }
        }

        /* There should be no rules with "ok" or "mark" as root symbols */
        if (splitRules.get(gState.getOk()) != null
                || splitRules.get(gState.getMark()) != null) {
            return false;
        }

        for (final Map.Entry<FunctionSymbol, Set<Rule>> entry : splitRules.entrySet()) {
            if (gState.getSpecials().contains(entry.getKey())) {
                continue;
            }
            for (final Rule r : entry.getValue()) {
                if (!this.isMarkRule(r, gState) && !this.isOkRule(r, gState)) {
                    return false;
                }
            }
        }

        return true;
    }

    /**
     * Checks if a rule is an "active" rule,
     *
     * i.e. of the form <code>active(l) -&gt; mark(r)</code> or
     * <code>active(f(x1, x2, ..., xn)) -&gt; f(x1, ..., active(xi), ..., xn).</code>
     *
     * @param r
     * @param gState
     * @return
     */
    private boolean isActiveRule(final Rule r, final GuessingState gState) {
        final FunctionSymbol active = gState.getActive();
        final FunctionSymbol mark = gState.getMark();

        if (Globals.useAssertions) {
            assert(r.getRootSymbol().equals(active));
        }

        if (r.getRight().isVariable()) {
            return false;
        }

        final TRSFunctionApplication rhsFa = (TRSFunctionApplication)r.getRight();
        final TRSTerm la0 = r.getLeft().getArgument(0);

        if (la0.isVariable()) {
            return false;
        }

        /* is this an active(l) -> mark(r) rule? */
        if (rhsFa.getRootSymbol().equals(mark)) {
            final TRSTerm ra0 = rhsFa.getArgument(0);

            return (this.isWithoutSpecials(la0, gState)
                    && this.isWithoutSpecials(ra0, gState));
        } else { /* is this an active(f(x1, ..., xn)) -> f(x1, ..., active(xi), ..., xn) rule? */
            return (!gState.isSpecial(rhsFa.getRootSymbol())
                    && this.hasSingleVarFuncApps(la0, rhsFa, active, 1));
        }
    }

    /**
     * Checks if a rule is an ok rule,
     *
     * <p>
     * i.e. of the form f(ok(x1), ..., ok(xn)) -> ok(f(x1, ..., xn)). Symbol f
     * is marked to have an ok rule in gState.
     * </p>
     */
    private boolean isOkRule(final Rule r, final GuessingState gState) {
        final FunctionSymbol ok = gState.getOk();
        if (gState.isSpecial(r.getRootSymbol()) || !this.hasRootSym(r.getRight(), ok)) {
            return false;
        }
        final TRSTerm ra0 = ((TRSFunctionApplication)r.getRight()).getArgument(0);
        if (this.hasSingleVarFuncApps(ra0, r.getLeft(), ok, -1)) {
            gState.setOkRule(r.getRootSymbol());
            return true;
        } else {
            return false;
        }
    }

    /**
     * Checks if a rule is a mark rule,
     *
     * <p>
     * i.e. of the form f(x1, ..., mark(xi), ..., xn) -> mark(f(x1, ..., xn)).
     * </p>
     */
    private boolean isMarkRule(final Rule r, final GuessingState gState) {
        final FunctionSymbol mark = gState.getMark();
        if (gState.isSpecial(r.getRootSymbol()) || !this.hasRootSym(r.getRight(), mark)) {
            return false;
        }
        final TRSTerm ra0 = ((TRSFunctionApplication)r.getRight()).getArgument(0);
        return this.hasSingleVarFuncApps(ra0, r.getLeft(), mark, 1);
    }

    /**
     * Checks if a rule is a proper rule,
     *
     * <p>
     * i.e. of the form proper(f(x1, ..., xn)) -> (f(proper(x1), ...,
     * proper(xn))) or of the form proper(c) -> ok(c). Symbol f
     * is marked to have an ok rule in gState.
     * </p>
     */
    private boolean isProperRule(final Rule r, final GuessingState gState) {
        final FunctionSymbol proper = gState.getProper();
        final FunctionSymbol ok = gState.getOk();

        if (Globals.useAssertions) {
            assert(r.getRootSymbol().equals(proper));
        }

        if (r.getRight().isVariable()) {
            return false;
        }

        final TRSFunctionApplication rhsFa = (TRSFunctionApplication)r.getRight();
        final TRSTerm la0 = r.getLeft().getArgument(0);

        if (la0.isVariable()) {
            return false;
        }
        final FunctionSymbol la0s = ((TRSFunctionApplication)la0).getRootSymbol();

        /* f may not be a special symbol */
        if (gState.isSpecial(la0s)) {
            return false;
        }

        /* is this an proper(c) -> ok(c) rule? */
        if (rhsFa.getRootSymbol().equals(ok)) {
            final TRSTerm ra0 = rhsFa.getArgument(0);
            if (la0s.getArity() == 0 && la0.equals(ra0)) {
                gState.setProperRule(la0s);
                return true;
            } else {
                return false;
            }
        } else { /* is this an proper(f(x1, ..., xn)) -> f(proper(x1), ..., proper(xn)) rule? */
            if (this.hasSingleVarFuncApps(la0, rhsFa, proper, -1)) {
                gState.setProperRule(la0s);
                return true;
            } else {
                return false;
            }
        }
    }

    /**
     * Checks that no of the special symbols occurs in a term.
     */
    private boolean isWithoutSpecials(final TRSTerm t, final GuessingState gState) {
        final Set<FunctionSymbol> syms = t.getFunctionSymbols();
        syms.retainAll(gState.getSpecials());
        return syms.isEmpty();
    }


    /**
     * Checks if t has the form fs(v) and v is an Variable.
     *
     * <p>fs must have arity 1.</p>
     */
    private boolean isSingleVarFuncApp(final TRSTerm t, final FunctionSymbol fs, final TRSTerm v) {
        if (Globals.useAssertions) {
            assert(fs.getArity() == 1);
        }
        if (t.isVariable()) {
            return false;
        }
        final TRSFunctionApplication fa = (TRSFunctionApplication)t;
        return fa.getRootSymbol().equals(fs)
                && fa.getArgument(0).equals(v)
                && v.isVariable();
    }

    /**
     * Checks if t1 = f(x1, ..., xk) and t2 = f(x1, ..., fs(xi), ..., fs(xj), ... xk)
     * with exactly n occurences of fs in the t2; k > 0;
     *
     * @param n -1 is interpreted as f.getArity().
     */
    private boolean hasSingleVarFuncApps(final TRSTerm t1, final TRSTerm t2, final FunctionSymbol fs, final int n) {
        if (t1.isVariable() || t2.isVariable()) {
            return false;
        }

        final TRSFunctionApplication fa1 = (TRSFunctionApplication)t1;
        final TRSFunctionApplication fa2 = (TRSFunctionApplication)t2;

        final FunctionSymbol f = fa1.getRootSymbol();
        if (f.getArity() == 0
                || !f.equals(fa2.getRootSymbol())) {
            return false;
        }

        int appCount = 0;
        for (int i=0; i < f.getArity(); i++) {
            final TRSTerm argi = fa1.getArgument(i);
            if (!argi.isVariable()) {
                return false;
            }
            if (fa2.getArgument(i).isVariable()) {
                continue;
            } else if (this.isSingleVarFuncApp(fa2.getArgument(i), fs, argi)) {
                appCount++;
            }
        }

        return (n == -1) ? appCount == f.getArity() : appCount == n;
    }

    /**
     * Checks that t is a FunctionApplication with root symbol fs.
     */
    private boolean hasRootSym(final TRSTerm t, final FunctionSymbol fs) {
        return !t.isVariable() && ((TRSFunctionApplication)t).getRootSymbol().equals(fs);
    }

    /**
     * Splits a set of rules by their root symbols.
     *
     * <p>
     * Returns a mapping of function symbol -> rules with this root symbol.
     * </p>
     */
    private Map<FunctionSymbol, Set<Rule>> splitRulesByRoot(final Set<Rule> rules) {
        final Map<FunctionSymbol, Set<Rule>> splitRules =
            new LinkedHashMap<FunctionSymbol, Set<Rule>>();

        for (final Rule r : rules) {
            final FunctionSymbol fs = r.getRootSymbol();
            Set<Rule> fsRules = splitRules.get(fs);
            if (fsRules == null) {
                fsRules = new LinkedHashSet<Rule>();
                splitRules.put(fs, fsRules);
            }
            fsRules.add(r);
        }
        return splitRules;
    }

    /**
     * Finds candidates for the "top" function symbol.
     *
     * @param splitRules
     *            A set of rules defining the TRS.
     * @return A mapping of candidates for the top symbol to candidates for the
     *         other special symbols. See also <code>checkTopCandidates</code>
     */
    private Map<FunctionSymbol, List<Pair<FunctionSymbol, FunctionSymbol>>>
            getTopCandidates(final Map<FunctionSymbol, Set<Rule>> splitRules) {
        final Map<FunctionSymbol, List<Pair<FunctionSymbol, FunctionSymbol>>> tcCandidates =
            new HashMap<FunctionSymbol, List<Pair<FunctionSymbol,FunctionSymbol>>>();
        for (final Entry<FunctionSymbol, Set<Rule>> entry : splitRules.entrySet()) {
            final List<Pair<FunctionSymbol, FunctionSymbol>> otherSymbolCandidates =
                this.checkTopCandidates(entry.getKey(), entry.getValue());
            if (otherSymbolCandidates != null) {
                tcCandidates.put(entry.getKey(), otherSymbolCandidates);
            }
        }

        return tcCandidates;
    }

    /**
     * Checks if a set of rules describes the "top" symbol.
     *
     * <p>
     * A set of rules describes the top symbol, iff it has the following form:
     * </p>
     *
     * <pre>
     * top(mark(x)) -&gt; top(proper(x))
     * top(ok(x)) -&gt; top(active(x))
     * </pre>
     *
     * <p>
     * In this case, a list is returned, containing the pairs (mark, proper) and
     * (ok, active). Which of the pairs is which remains to be checked.
     * </p>
     */
    private List<Pair<FunctionSymbol,FunctionSymbol>> checkTopCandidates(final FunctionSymbol root, final Set<Rule> rules) {
        if (rules.size() != 2) {
            return null;
        }

        final List<Pair<FunctionSymbol,FunctionSymbol>> otherSymbolCandidates =
            new ArrayList<Pair<FunctionSymbol,FunctionSymbol>>(2);

        for (final Rule r : rules) {
            final FunctionSymbol lfs = r.getRootSymbol();

            if (Globals.useAssertions) {
                assert(lfs.equals(root));
            }

            if (lfs.getArity() != 1
                    || r.getRight().isVariable()) {
                return null;
            }

            final TRSFunctionApplication lhs = r.getLeft();
            final TRSFunctionApplication rhs = (TRSFunctionApplication)r.getRight();

            if (!lfs.equals(rhs.getRootSymbol())) {
                return null;
            }

            final TRSTerm la0 = lhs.getArgument(0);
            final TRSTerm ra0 = rhs.getArgument(0);

            if (la0.isVariable() || ra0.isVariable()) {
                return null;
            }

            final TRSFunctionApplication la0F = (TRSFunctionApplication)la0;
            final TRSFunctionApplication ra0F = (TRSFunctionApplication)ra0;

            final FunctionSymbol la0S = la0F.getRootSymbol();
            final FunctionSymbol ra0S = ra0F.getRootSymbol();

            if (la0S.getArity() != 1 || ra0S.getArity() != 1
                    || la0S.equals(ra0S)
                    || !la0F.getArgument(0).isVariable()
                    || !ra0F.getArgument(0).isVariable()) {
                return null;
            }

            otherSymbolCandidates.add(
                    new Pair<FunctionSymbol, FunctionSymbol>(la0S, ra0S));
        }

        final Set<FunctionSymbol> joinNTC = new HashSet<FunctionSymbol>(5);
        for (final Pair<FunctionSymbol,FunctionSymbol> p : otherSymbolCandidates) {
           joinNTC.add(p.x);
           joinNTC.add(p.y);
        }
        joinNTC.add(root);
        if (joinNTC.size() != 5) {
            return null;
        } else {
            return otherSymbolCandidates;
        }
    }

}

class QTRSToCSRProof extends QTRSProof {

    private final QTRSProblem qtrs;
    private final CSRProblem csr;
    private final FunctionSymbol top;
    private final FunctionSymbol active;
    private final FunctionSymbol mark;
    private final FunctionSymbol ok;
    private final FunctionSymbol proper;
    private final boolean complete;

    public QTRSToCSRProof(final QTRSProblem qtrs, final CSRProblem csr,
            final GuessingState specialSyms, final boolean complete) {

        this.qtrs = qtrs;
        this.csr = csr;
        this.top = specialSyms.getTop();
        this.active = specialSyms.getActive();
        this.mark = specialSyms.getMark();
        this.ok = specialSyms.getOk();
        this.proper = specialSyms.getProper();
        this.complete = complete;
    }

    @Override
    public String export(final Export_Util o, final VerbosityLevel l) {
        StringBuilder result;
        result = new StringBuilder();
        result.append("The following Q TRS is given: ");
        result.append(this.qtrs.export(o));
        result.append("Special symbols used for the transformation (see ");
        result.append(o.cite(Citation.GM04));
        result.append("):");
        result.append(o.linebreak());
        result.append("top: ");
        result.append(o.export(this.top));
        result.append(", active: ");
        result.append(o.export(this.active));
        result.append(", mark: ");
        result.append(o.export(this.mark));
        result.append(", ok: ");
        result.append(o.export(this.ok));
        result.append(", proper: ");
        result.append(o.export(this.proper));
        result.append(o.linebreak());
        result.append("The replacement map contains the following entries:"+o.paragraph());
        for (final Map.Entry<FunctionSymbol, ? extends Set<Integer>> repMapEntry : this.csr.getReplacementMap().entrySet()) {
            final Set<Integer> repl = repMapEntry.getValue();
            final ArrayList<Integer> shiftSet = new ArrayList<Integer>(repl.size());
            for (final Integer i : repl) {
                shiftSet.add(i+1);
            }
            result.append(repMapEntry.getKey().export(o)+": "+o.set(shiftSet, Export_Util.SIMPLESET)+o.cond_linebreak());
        }
        if (this.complete) {
            result.append("The QTRS contained all rules created by the " +
                    "complete Giesl-Middeldorp transformation. Therefore, " +
                    "the inverse transformation is complete (and sound).");
        } else {
            result.append("The QTRS contained just a subset of rules " +
                    "created by the complete Giesl-Middeldorp " +
                    "transformation. Therefore, the inverse transformation " +
                    "is sound, but not necessarily complete.");
        }
        return result.toString();
    }

}

/**
 * Contains a guessing state for the special symbols.
 */
class GuessingState {

    private final FunctionSymbol top;
    private final FunctionSymbol markOk[];
    private final FunctionSymbol properActive[];
    private final Set<FunctionSymbol> specials;

    private final Set<FunctionSymbol> hasProperRule;
    private final Set<FunctionSymbol> hasOkRule;

    private int idx = 0;
    private boolean complete = true;

    public GuessingState(final FunctionSymbol top, final List<Pair<FunctionSymbol,FunctionSymbol>> others) {
        this.top = top;
        this.markOk =
            new FunctionSymbol[] {others.get(0).x, others.get(1).x};
        this.properActive =
            new FunctionSymbol[] {others.get(0).y, others.get(1).y};

        this.hasProperRule = new LinkedHashSet<FunctionSymbol>();
        this.hasOkRule = new LinkedHashSet<FunctionSymbol>();

        final Set<FunctionSymbol> s = new LinkedHashSet<FunctionSymbol>(5);
        s.add(this.top);
        s.add(this.markOk[0]);
        s.add(this.markOk[1]);
        s.add(this.properActive[0]);
        s.add(this.properActive[1]);
        this.specials = java.util.Collections.unmodifiableSet(s);
    }

    /**
     * Switches to the next guessing state.
     *
     * <p>For each top symbol, there are exactly two possibilities for the other
     * four special symbols. This method switches to the next possibility.</p>
     *
     * <p>This includes resetting any completeness informations, generated by
     * setNotComplete(), setOkRule and setProperRule</p>
     */
    public void next() {
        this.idx = (this.idx + 1) % 2;

        this.hasOkRule.clear();
        this.hasProperRule.clear();
        this.complete = true;
    }

    public FunctionSymbol getTop() {
        return this.top;
    }

    public FunctionSymbol getMark() {
        return this.markOk[this.idx];
    }

    public FunctionSymbol getProper() {
        return this.properActive[this.idx];
    }

    public FunctionSymbol getOk() {
        return this.markOk[(this.idx + 1) % 2];
    }

    public FunctionSymbol getActive() {
        return this.properActive[(this.idx + 1) % 2];
    }

    /**
     * Returns a set of the special symbols.
     */
    public Set<FunctionSymbol> getSpecials() {
        return this.specials;
    }

    public boolean isSpecial(final FunctionSymbol sym) {
        return this.specials.contains(sym);
    }

    /**
     * Marks a function symbol as having an ok rule.
     */
    public boolean setOkRule(final FunctionSymbol fs) {
        return this.hasOkRule.add(fs);
    }

    /**
     * Marks a function symbol as having a proper rule.
     */
    public boolean setProperRule(final FunctionSymbol fs) {
        return this.hasProperRule.add(fs);
    }

    /**
     * Notes that a transformation with these special symbols is just sound, not
     * complete.
     */
    public void setNotComplete() {
        this.complete = false;
    }

    /**
     * Checks completeness information.
     *
     * <p>Returns true iff setNotComplete() was not called and each non-special
     * function symbol in signature has a proper rule as well as an ok rule.</p>
     */
    public boolean checkComplete(final Set<FunctionSymbol> signature) {
        if (!this.complete) {
            return false;
        }
        final Set<FunctionSymbol> sig = new LinkedHashSet<FunctionSymbol>(signature);
        sig.removeAll(this.specials);

        /* every non-special symbol must have a "proper" rule */
        if (!this.hasProperRule.equals(sig)) {
            return false;
        }

        /*
         * every non-special non-constant symbol f must have an f(...)->ok(...)
         * rule.
         */
        if (!sig.containsAll(this.hasOkRule)) {
            return false;
        }
        sig.removeAll(this.hasOkRule);
        for (final FunctionSymbol sym : sig) {
            if (sym.getArity() != 0) {
                return false;
            }
        }

        return true;
    }

}
